//! Fourth corewire projection: the plain-scriptc service host entry and the
//! Zig name/index registry consumed by the runner transport.

const std = @import("std");
const service = @import("service_contract.zig");

const fingerprint_len = std.crypto.hash.sha2.Sha256.digest_length;

fn fingerprintField(hasher: *std.crypto.hash.sha2.Sha256, bytes: []const u8) void {
    var len: [8]u8 = undefined;
    std.mem.writeInt(u64, &len, @intCast(bytes.len), .little);
    hasher.update(&len);
    hasher.update(bytes);
}

/// Identity of every fact that can change generated dispatch semantics. The
/// same digest is embedded in the service executable and the Zig registry so
/// a stale or hand-supplied sibling is refused before numeric indices are used.
fn contractFingerprint(contract: service.Contract) [fingerprint_len]u8 {
    var hasher = std.crypto.hash.sha2.Sha256.init(.{});
    hasher.update("native-sdk.services.contract.v1\x00");
    var scalar: [8]u8 = undefined;
    std.mem.writeInt(i64, &scalar, contract.format, .little);
    hasher.update(&scalar);
    std.mem.writeInt(i64, &scalar, contract.protocol_version, .little);
    hasher.update(&scalar);
    hasher.update(&.{@intFromBool(contract.deterministic)});
    fingerprintField(&hasher, contract.compiler_version);
    std.mem.writeInt(u64, &scalar, @intCast(contract.operations.len), .little);
    hasher.update(&scalar);
    for (contract.operations) |op| {
        fingerprintField(&hasher, op.name);
        fingerprintField(&hasher, op.module);
        fingerprintField(&hasher, op.@"export");
        hasher.update(&.{ @intFromEnum(op.payload), @intFromEnum(op.result) });
        fingerprintField(&hasher, op.source_hash);
    }
    return hasher.finalResult();
}

pub fn emitHost(arena: std.mem.Allocator, contract: service.Contract) ![]const u8 {
    var out = std.Io.Writer.Allocating.init(arena);
    const w = &out.writer;
    try w.writeAll(
        \\// Generated by corewire from services.contract.json. Do not edit.
        \\import * as fs from "node:fs";
        \\
    );
    for (contract.operations, 0..) |op, index| {
        const staged_module = op.module["src/".len..];
        try w.print("import {{ {s} as serviceOp{d} }} from \"./{s}\";\n", .{ op.@"export", index, staged_module });
    }
    const fingerprint = contractFingerprint(contract);
    try w.print("\nconst PROTOCOL_VERSION = {d};\nconst CONTRACT_FINGERPRINT = new Uint8Array([", .{contract.protocol_version});
    for (fingerprint, 0..) |byte, index| {
        if (index > 0) try w.writeAll(", ");
        try w.print("{d}", .{byte});
    }
    try w.writeAll("]);\n");
    try w.writeAll(
        \\const MAX_FRAME_BYTES = 16 * 1024 * 1024;
        \\function readExact(length: number, eofAllowed: boolean): Uint8Array | null {
        \\  const bytes = new Uint8Array(length);
        \\  let offset = 0;
        \\  while (offset < length) {
        \\    const read = fs.readSync(0, bytes, offset, length - offset);
        \\    if (read === 0) {
        \\      if (offset === 0 && eofAllowed) return null;
        \\      throw { kind: "service_protocol", message: "truncated frame" };
        \\    }
        \\    offset += read;
        \\  }
        \\  return bytes;
        \\}
        \\
        \\function u16(bytes: Uint8Array, at: number): number {
        \\  return bytes[at] | (bytes[at + 1] << 8);
        \\}
        \\function u32(bytes: Uint8Array, at: number): number {
        \\  return (bytes[at] | (bytes[at + 1] << 8) | (bytes[at + 2] << 16) | (bytes[at + 3] << 24)) >>> 0;
        \\}
        \\function putU32(bytes: Uint8Array, at: number, value: number): void {
        \\  bytes[at] = value & 255;
        \\  bytes[at + 1] = (value >>> 8) & 255;
        \\  bytes[at + 2] = (value >>> 16) & 255;
        \\  bytes[at + 3] = (value >>> 24) & 255;
        \\}
        \\function writeHello(): void {
        \\  const frame = new Uint8Array(5 + CONTRACT_FINGERPRINT.length);
        \\  putU32(frame, 0, 1 + CONTRACT_FINGERPRINT.length);
        \\  frame[4] = PROTOCOL_VERSION;
        \\  frame.set(CONTRACT_FINGERPRINT, 5);
        \\  process.stdout.write(frame);
        \\}
        \\function writeResult(requestId: number, ok: boolean, payload: Uint8Array): void {
        \\  const frame = new Uint8Array(9 + payload.length);
        \\  putU32(frame, 0, 5 + payload.length);
        \\  putU32(frame, 4, requestId);
        \\  frame[8] = ok ? 0 : 1;
        \\  frame.set(payload, 9);
        \\  process.stdout.write(frame);
        \\}
        \\
        \\function dispatch(index: number, payload: Uint8Array): Uint8Array {
        \\  switch (index) {
    );
    for (contract.operations, 0..) |op, index| {
        switch (op.payload) {
            .none => try w.print("    case {d}: return serviceOp{d}();\n", .{ index, index }),
            .bytes => try w.print("    case {d}: return serviceOp{d}(payload);\n", .{ index, index }),
        }
    }
    try w.writeAll(
        \\    default: throw new Error("service operation index is not in the contract");
        \\  }
        \\}
        \\
        \\writeHello();
        \\while (true) {
        \\  const header = readExact(4, true);
        \\  if (header === null) break;
        \\  const length = u32(header, 0);
        \\  if (length < 6 || length > MAX_FRAME_BYTES) throw { kind: "service_protocol", message: "invalid request frame length" };
        \\  const body = readExact(length, false) as Uint8Array;
        \\  const requestId = u32(body, 0);
        \\  const operation = u16(body, 4);
        \\  const payload = body.subarray(6);
        \\  try {
        \\    writeResult(requestId, true, dispatch(operation, payload));
        \\  } catch (error) {
        \\    if (error instanceof Error) {
        \\      writeResult(requestId, false, new TextEncoder().encode(JSON.stringify({ kind: error.name, message: error.message })));
        \\    } else {
        \\      writeResult(requestId, false, new TextEncoder().encode(JSON.stringify({ kind: "service_error", message: "service operation threw" })));
        \\    }
        \\  }
        \\}
        \\
    );
    return out.toOwnedSlice();
}

pub fn emitRegistry(arena: std.mem.Allocator, contract: service.Contract) ![]const u8 {
    var out = std.Io.Writer.Allocating.init(arena);
    const w = &out.writer;
    const fingerprint = contractFingerprint(contract);
    try w.print(
        \\//! Generated by corewire from services.contract.json. Do not edit.
        \\pub const enabled = true;
        \\pub const protocol_version: u8 = {d};
        \\pub const compiler_version = "{s}";
        \\
    , .{ contract.protocol_version, contract.compiler_version });
    try w.writeAll("pub const contract_fingerprint = [_]u8{");
    for (fingerprint, 0..) |byte, index| {
        if (index > 0) try w.writeAll(", ");
        try w.print("{d}", .{byte});
    }
    try w.writeAll(
        \\};
        \\pub const Operation = struct { name: []const u8, index: u16 };
        \\pub const operations = [_]Operation{
        \\
    );
    for (contract.operations, 0..) |op, index| {
        try w.print("    .{{ .name = \"{s}\", .index = {d} }},\n", .{ op.name, index });
    }
    try w.writeAll(
        \\};
        \\pub fn indexOf(name: []const u8) ?u16 {
        \\    for (operations) |op| if (@import("std").mem.eql(u8, op.name, name)) return op.index;
        \\    return null;
        \\}
        \\
    );
    return out.toOwnedSlice();
}

test "service projection derives host dispatch and registry from one contract" {
    const operations = [_]service.Operation{
        .{
            .name = "feeds.parse",
            .module = "src/services/feeds.ts",
            .@"export" = "parse",
            .payload = .bytes,
            .result = .bytes,
            .source_hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        },
        .{
            .name = "feeds.$refresh",
            .module = "src/services/feeds.ts",
            .@"export" = "$refresh",
            .payload = .none,
            .result = .bytes,
            .source_hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        },
    };
    const contract: service.Contract = .{
        .format = 1,
        .protocol_version = 1,
        .compiler_version = "0.0.22",
        .deterministic = false,
        .operations = &operations,
    };

    const host = try emitHost(std.testing.allocator, contract);
    defer std.testing.allocator.free(host);
    try std.testing.expect(std.mem.indexOf(u8, host, "serviceOp0(payload)") != null);
    try std.testing.expect(std.mem.indexOf(u8, host, "serviceOp1()") != null);
    try std.testing.expect(std.mem.indexOf(u8, host, "import { $refresh as serviceOp1 }") != null);
    try std.testing.expect(std.mem.indexOf(u8, host, "PROTOCOL_VERSION = 1") != null);
    try std.testing.expect(std.mem.indexOf(u8, host, "CONTRACT_FINGERPRINT = new Uint8Array([") != null);

    const registry = try emitRegistry(std.testing.allocator, contract);
    defer std.testing.allocator.free(registry);
    try std.testing.expect(std.mem.indexOf(u8, registry, ".name = \"feeds.parse\", .index = 0") != null);
    try std.testing.expect(std.mem.indexOf(u8, registry, "pub const compiler_version = \"0.0.22\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, registry, "pub const contract_fingerprint = [_]u8{") != null);

    const original_fingerprint = contractFingerprint(contract);
    const reordered_operations = [_]service.Operation{ operations[1], operations[0] };
    const reordered_fingerprint = contractFingerprint(.{
        .format = contract.format,
        .protocol_version = contract.protocol_version,
        .compiler_version = contract.compiler_version,
        .deterministic = contract.deterministic,
        .operations = &reordered_operations,
    });
    try std.testing.expect(!std.mem.eql(u8, &original_fingerprint, &reordered_fingerprint));
}
