import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, writeFileSync } from "node:fs";
import { NativeApp, findWidget, type NativeSnapshot } from "@native-sdk/core/testing";
const backend = process.env.NATIVE_SDK_TEST_VIEW_BACKEND;
const row = (s: NativeSnapshot, name: string) => findWidget(s, { role: "listitem", name });
const button = (s: NativeSnapshot, name: string) => findWidget(s, { role: "button", name });
const compare = (snapshots: NativeSnapshot[]) => {
  const reference = process.env.NATIVE_SDK_TEST_VIEW_REFERENCE;
  if (!reference) return;
  const values = snapshots.map(({ viewBackend, ...s }) => s);
  if (backend === "zig") writeFileSync(`${reference}.navigation.json`, JSON.stringify(values));
  else assert.deepEqual(values, JSON.parse(readFileSync(`${reference}.navigation.json`, "utf8")));
};
test("list focus, scroll reveal, nested selection, identity and replay match", async () => {
  const app = await NativeApp.start({ width: 800, height: 440 });
  try {
    let s = await app.snapshot();
    if (backend) assert.equal(s.viewBackend, backend);
    const snapshots = [s], view = row(s, "Build plan").view;
    const reviewId = row(s, "Review café").id, followId = row(s, "Follow up").id;
    const record = (focused: string, selected: number, presses: number) => {
      assert.equal(row(s, focused).focused, true, JSON.stringify(s.widgets.filter(w => w.focused)));
      assert.equal(s.model.selected, selected);
      assert.equal(s.model.presses, presses);
      assert.equal(s.widgets.filter(w => w.role === "listitem" && w.selected).length, 3);
      snapshots.push(s);
    };
    // Pointer routing from a composed child's title reaches its row.
    const title = findWidget(s, { role: "text", name: "Review café" });
    s = await app.click(title); record("Review café", 2, 1);
    s = await app.key(view, "arrowdown"); record("Review café", 2, 1);
    s = await app.key(view, "shift+tab"); record("Build plan", 2, 1);
    s = await app.key(view, "tab"); record("Review café", 2, 1);
    s = await app.key(view, "arrowdown"); record("Update docs", 2, 1);
    s = await app.key(view, "enter"); record("Update docs", 4, 2);
    s = await app.key(view, "arrowdown"); record("Ship release", 4, 2);
    s = await app.key(view, "arrowdown"); record("Follow up", 4, 2);
    const scroll = findWidget(s, { role: "group", name: "Work items" });
    const revealed = row(s, "Follow up");
    assert.ok(revealed.bounds.y >= scroll.bounds.y);
    assert.ok(revealed.bounds.y + revealed.bounds.height <= scroll.bounds.y + scroll.bounds.height);
    s = await app.key(view, "arrowdown"); record("Follow up", 4, 2);
    s = await app.key(view, "space"); record("Follow up", 6, 3);
    s = await app.key(view, "arrowup"); record("Ship release", 6, 3);
    s = await app.key(view, "arrowup"); record("Update docs", 6, 3);
    s = await app.key(view, "arrowup"); record("Review café", 6, 3);
    s = await app.key(view, "arrowup"); record("Build plan", 6, 3);
    s = await app.key(view, "arrowup"); record("Build plan", 6, 3);
    s = await app.key(view, "home"); record("Build plan", 6, 3);
    // Home/End choose visible direct siblings, without changing selection.
    s = await app.key(view, "end"); record("Update docs", 6, 3);
    s = await app.key(view, "enter"); record("Update docs", 4, 4);
    const unavailable = row(s, "Unavailable item");
    assert.equal(unavailable.enabled, false);
    const point = { x: unavailable.bounds.x + 10, y: unavailable.bounds.y + 10 };
    await app.pointer(unavailable, "down", point);
    s = await app.pointer(unavailable, "up", point); assert.equal(s.model.selected, 4); snapshots.push(s);
    s = await app.click(row(s, "Later")); assert.equal(s.model.secondary, 102); snapshots.push(s);
    s = await app.key(view, "home"); assert.equal(row(s, "Later").focused, true); snapshots.push(s);
    await app.key(view, "shift+tab"); s = await app.key(view, "tab"); snapshots.push(s);
    s = await app.key(view, "home"); assert.equal(row(s, "Inbox").focused, true); assert.equal(s.model.secondary, 102); snapshots.push(s);
    s = await app.key(view, "enter"); assert.equal(s.model.secondary, 101); snapshots.push(s);
    s = await app.key(view, "end"); assert.equal(row(s, "Later").focused, true); snapshots.push(s);
    s = await app.key(view, "arrowdown"); assert.equal(row(s, "Later").focused, true); snapshots.push(s);
    s = await app.click(row(s, "Archive")); assert.equal(s.model.nested, 202); assert.equal(s.model.secondary, 101); assert.equal(s.model.selected, 4); snapshots.push(s);
    await app.key(view, "shift+tab"); s = await app.key(view, "tab"); snapshots.push(s);
    s = await app.key(view, "home"); assert.equal(row(s, "Pinned").focused, true); snapshots.push(s);
    s = await app.key(view, "space"); assert.equal(s.model.nested, 201); snapshots.push(s);
    s = await app.click(button(s, "Reverse")); assert.equal(row(s, "Follow up").id, followId); snapshots.push(s);
    s = await app.wheel(findWidget(s, { role: "group", name: "Work items" }), -1000); snapshots.push(s);
    s = await app.click(row(s, "Follow up")); record("Follow up", 6, 5);
    await app.key(view, "shift+tab"); s = await app.key(view, "tab"); record("Follow up", 6, 5);
    s = await app.key(view, "arrowdown"); record("Ship release", 6, 5);
    s = await app.key(view, "arrowdown"); record("Update docs", 6, 5);
    s = await app.key(view, "arrowdown"); record("Review café", 6, 5);
    s = await app.key(view, "enter"); record("Review café", 2, 6);
    s = await app.click(button(s, "Hide review")); assert.equal(s.widgets.some(w => w.name === "Review café"), false); assert.equal(s.model.selected, 2); snapshots.push(s);
    s = await app.click(button(s, "Hide review")); assert.equal(row(s, "Review café").id, reviewId); assert.equal(row(s, "Review café").selected, true); snapshots.push(s);
    s = await app.click(button(s, "Empty")); assert.equal(s.widgets.filter(w => w.role === "listitem").length, 4); snapshots.push(s);
    s = await app.click(button(s, "Empty")); assert.equal(row(s, "Review café").id, reviewId); assert.equal(row(s, "Review café").selected, true); snapshots.push(s);
    s = await app.click(button(s, "Reset")); snapshots.push(s);
    s = await app.key(view, "tab"); assert.equal(findWidget(s, { role: "group", name: "Work items" }).focused, true); snapshots.push(s);
    s = await app.key(view, "tab"); record("Build plan", 1, 0);
    s = await app.key(view, "tab"); record("Review café", 1, 0);
    s = await app.key(view, "shift+tab"); record("Build plan", 1, 0);
    const replay = await app.verifyReplay();
    assert.deepEqual(replay.snapshot.model, s.model);
    assert.deepEqual(replay.snapshot.widgets, s.widgets); snapshots.push(replay.snapshot);
    compare(snapshots);
  } finally { await app.close(); }
});
