import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, writeFileSync } from "node:fs";
import { NativeApp, findWidget, type NativeSnapshot } from "@native-sdk/core/testing";
const backend = process.env.NATIVE_SDK_TEST_VIEW_BACKEND;
const row = (s: NativeSnapshot, name: string) => findWidget(s, { role: "treeitem", name });
const button = (s: NativeSnapshot, name: string) => findWidget(s, { role: "button", name });
const compare = (snapshots: NativeSnapshot[]) => {
  const reference = process.env.NATIVE_SDK_TEST_VIEW_REFERENCE;
  if (!reference) return;
  const values = snapshots.map(({ viewBackend, ...s }) => s);
  if (backend === "zig") writeFileSync(`${reference}.navigation.json`, JSON.stringify(values));
  else assert.deepEqual(values, JSON.parse(readFileSync(`${reference}.navigation.json`, "utf8")));
};
test("tree flat and nested hierarchy, disclosure, selection, identity and replay match", async () => {
  const app = await NativeApp.start({ width: 760, height: 640 });
  try {
    let s = await app.snapshot();
    if (backend) assert.equal(s.viewBackend, backend);
    const snapshots = [s], view = row(s, "Source").view;
    const coreId = row(s, "Core café.ts").id, appId = row(s, "App.native").id;
    const landed = (name: string, selected: number) => {
      assert.equal(row(s, name).focused, true);
      assert.equal(row(s, name).selected, true);
      assert.equal(s.model.selected, selected);
      assert.equal(s.widgets.filter(w => w.role === "treeitem" && w.selected).length, 2);
      snapshots.push(s);
    };
    s = await app.click(row(s, "Source")); landed("Source", 1);
    s = await app.key(view, "arrowright"); landed("Core café.ts", 11);
    s = await app.key(view, "arrowdown"); landed("App.native", 12);
    s = await app.key(view, "arrowdown"); landed("README.md", 2);
    const presses = s.model.presses;
    s = await app.key(view, "arrowdown"); landed("README.md", 2); assert.equal(s.model.presses, presses);
    s = await app.key(view, "arrowup"); landed("App.native", 12);
    s = await app.key(view, "arrowleft"); landed("Source", 1);
    s = await app.key(view, "arrowleft");
    assert.equal(s.model.expanded, false);
    assert.equal(s.widgets.some(w => w.name === "Core café.ts"), false); snapshots.push(s);
    s = await app.key(view, "arrowright");
    assert.equal(s.model.expanded, true);
    assert.equal(row(s, "Core café.ts").id, coreId); snapshots.push(s);
    s = await app.key(view, "end"); landed("README.md", 2);
    s = await app.key(view, "home"); landed("Source", 1);
    s = await app.key(view, "arrowup"); landed("Source", 1);
    s = await app.key(view, "enter"); landed("Source", 1);
    s = await app.key(view, "space"); landed("Source", 1);
    const unavailable = row(s, "Unavailable.ts");
    assert.equal(unavailable.enabled, false);
    const point = { x: unavailable.bounds.x + unavailable.bounds.width / 2, y: unavailable.bounds.y + unavailable.bounds.height / 2 };
    await app.pointer(unavailable, "down", point);
    s = await app.pointer(unavailable, "up", point); assert.equal(s.model.selected, 1); snapshots.push(s);
    await app.action(row(s, "Assets"), "focus");
    s = await app.key(view, "enter"); landed("Assets", 3);
    s = await app.key(view, "arrowright"); landed("Icon.png", 31);
    s = await app.key(view, "arrowdown"); landed("Font.woff2", 32);
    s = await app.key(view, "arrowleft"); landed("Assets", 3);
    s = await app.key(view, "arrowleft");
    assert.equal(s.model.nestedExpanded, false); assert.equal(s.widgets.some(w => w.name === "Icon.png"), false); snapshots.push(s);
    s = await app.key(view, "arrowright"); assert.equal(s.model.nestedExpanded, true); snapshots.push(s);
    s = await app.key(view, "end"); landed("Font.woff2", 32);
    s = await app.key(view, "home"); landed("Assets", 3);
    s = await app.click(row(s, "Drafts")); assert.equal(s.model.secondary, 102); assert.equal(s.model.selected, 3); snapshots.push(s);
    s = await app.key(view, "home"); assert.equal(s.model.secondary, 101); assert.equal(row(s, "Archive").focused, true); snapshots.push(s);
    s = await app.click(button(s, "Reverse")); assert.equal(row(s, "App.native").id, appId); snapshots.push(s);
    await app.action(row(s, "Source"), "focus");
    s = await app.key(view, "arrowright"); landed("App.native", 12);
    s = await app.key(view, "arrowdown"); landed("Core café.ts", 11);
    s = await app.click(button(s, "Hide core"));
    assert.equal(s.widgets.some(w => w.name === "Core café.ts"), false); assert.equal(s.model.selected, 11); snapshots.push(s);
    s = await app.click(button(s, "Hide core")); assert.equal(row(s, "Core café.ts").id, coreId); assert.equal(row(s, "Core café.ts").selected, true); snapshots.push(s);
    await app.action(button(s, "Reset"), "focus");
    s = await app.key(view, "tab"); assert.equal(row(s, "Source").focused, true); snapshots.push(s);
    s = await app.key(view, "tab"); assert.equal(row(s, "App.native").focused, true); snapshots.push(s);
    s = await app.key(view, "shift+tab"); assert.equal(row(s, "Source").focused, true); snapshots.push(s);
    const replay = await app.verifyReplay();
    assert.deepEqual(replay.snapshot.model, s.model);
    assert.deepEqual(replay.snapshot.widgets, s.widgets); snapshots.push(replay.snapshot);
    compare(snapshots);
  } finally { await app.close(); }
});
