const platform = @import("../platform/root.zig");

pub const max_mobile_command_name_bytes: usize = 128;
pub const max_mobile_input_text_bytes: usize = 512;
pub const max_mobile_asset_root_bytes: usize = platform.max_webview_url_bytes;
pub const max_mobile_asset_entry_bytes: usize = platform.max_window_source_bytes;
pub const mobile_gpu_surface_label = "mobile-surface";

pub const MobileWidgetRole = enum(c_int) {
    none = 0,
    group = 1,
    text = 2,
    image = 3,
    button = 4,
    textbox = 5,
    tooltip = 6,
    dialog = 7,
    menu = 8,
    menuitem = 9,
    list = 10,
    listitem = 11,
    row = 12,
    grid = 13,
    gridcell = 14,
    tab = 15,
    checkbox = 16,
    switch_control = 17,
    slider = 18,
    progressbar = 19,
    radio = 20,
};

pub const MobileWidgetFlag = enum(u32) {
    focused = 1 << 0,
    hovered = 1 << 1,
    pressed = 1 << 2,
    selected = 1 << 3,
    disabled = 1 << 4,
    focusable = 1 << 5,
    expanded = 1 << 6,
    collapsed = 1 << 7,
    required = 1 << 8,
    read_only = 1 << 9,
    invalid = 1 << 10,
};

pub const MobileWidgetAction = enum(u32) {
    focus = 1 << 0,
    press = 1 << 1,
    toggle = 1 << 2,
    increment = 1 << 3,
    decrement = 1 << 4,
    set_text = 1 << 5,
    set_selection = 1 << 6,
    select = 1 << 7,
    drag = 1 << 8,
    drop_files = 1 << 9,
    dismiss = 1 << 10,
};

pub const MobileWidgetActionKind = enum(c_int) {
    focus = 0,
    press = 1,
    toggle = 2,
    increment = 3,
    decrement = 4,
    set_text = 5,
    set_selection = 6,
    set_composition = 7,
    commit_composition = 8,
    cancel_composition = 9,
    select = 10,
    drag = 11,
    drop_files = 12,
    dismiss = 13,
};

pub const MobileWidgetSemantics = extern struct {
    id: u64 = 0,
    parent_id: u64 = 0,
    role: c_int = @intFromEnum(MobileWidgetRole.none),
    flags: u32 = 0,
    actions: u32 = 0,
    x: f32 = 0,
    y: f32 = 0,
    width: f32 = 0,
    height: f32 = 0,
    value: f32 = 0,
    has_value: c_int = 0,
    label: ?[*]const u8 = null,
    label_len: usize = 0,
    text: ?[*]const u8 = null,
    text_len: usize = 0,
    placeholder: ?[*]const u8 = null,
    placeholder_len: usize = 0,
    text_selection_start: isize = -1,
    text_selection_end: isize = -1,
    text_composition_start: isize = -1,
    text_composition_end: isize = -1,
    grid_row_index: isize = -1,
    grid_column_index: isize = -1,
    grid_row_count: isize = -1,
    grid_column_count: isize = -1,
    list_item_index: isize = -1,
    list_item_count: isize = -1,
    scroll_offset: f32 = 0,
    scroll_viewport_extent: f32 = 0,
    scroll_content_extent: f32 = 0,
    has_scroll: c_int = 0,
};

pub const MobileWidgetTextGeometry = extern struct {
    id: u64 = 0,
    has_caret_bounds: c_int = 0,
    caret_x: f32 = 0,
    caret_y: f32 = 0,
    caret_width: f32 = 0,
    caret_height: f32 = 0,
    has_selection_bounds: c_int = 0,
    selection_x: f32 = 0,
    selection_y: f32 = 0,
    selection_width: f32 = 0,
    selection_height: f32 = 0,
    selection_rect_count: usize = 0,
    has_composition_bounds: c_int = 0,
    composition_x: f32 = 0,
    composition_y: f32 = 0,
    composition_width: f32 = 0,
    composition_height: f32 = 0,
    composition_rect_count: usize = 0,
};

pub const MobileWidgetActionRequest = extern struct {
    id: u64 = 0,
    action: c_int = @intFromEnum(MobileWidgetActionKind.focus),
    text: ?[*]const u8 = null,
    text_len: usize = 0,
    selection_anchor: usize = 0,
    selection_focus: usize = 0,
    has_selection: c_int = 0,
};

pub const MobileViewportState = extern struct {
    width: f32 = 0,
    height: f32 = 0,
    scale: f32 = 1,
    has_surface: c_int = 0,
    safe_top: f32 = 0,
    safe_right: f32 = 0,
    safe_bottom: f32 = 0,
    safe_left: f32 = 0,
    keyboard_top: f32 = 0,
    keyboard_right: f32 = 0,
    keyboard_bottom: f32 = 0,
    keyboard_left: f32 = 0,
    content_x: f32 = 0,
    content_y: f32 = 0,
    content_width: f32 = 0,
    content_height: f32 = 0,
};

pub const MobileGpuFrameState = extern struct {
    surface_id: u64 = 0,
    window_id: u64 = 0,
    width: f32 = 0,
    height: f32 = 0,
    scale: f32 = 1,
    frame_index: u64 = 0,
    timestamp_ns: u64 = 0,
    frame_interval_ns: u64 = platform.default_gpu_frame_interval_ns,
    input_timestamp_ns: u64 = 0,
    input_latency_ns: u64 = 0,
    input_latency_budget_ns: u64 = platform.default_gpu_frame_interval_ns,
    input_latency_budget_exceeded_count: usize = 0,
    input_latency_budget_ok: c_int = 1,
    first_frame_latency_ns: u64 = 0,
    first_frame_latency_budget_ns: u64 = platform.default_gpu_first_frame_latency_budget_ns,
    first_frame_latency_budget_exceeded_count: usize = 0,
    first_frame_latency_budget_ok: c_int = 1,
    nonblank: c_int = 0,
    sample_color: u32 = 0,
    status: c_int = @intFromEnum(platform.GpuSurfaceStatus.unavailable),
    vsync: c_int = 0,
    canvas_revision: u64 = 0,
    canvas_command_count: usize = 0,
    canvas_frame_requires_render: c_int = 0,
    canvas_frame_full_repaint: c_int = 0,
    canvas_frame_batch_count: usize = 0,
    canvas_frame_budget_exceeded_count: usize = 0,
    canvas_frame_budget_ok: c_int = 1,
    widget_revision: u64 = 0,
    widget_node_count: usize = 0,
    widget_semantics_count: usize = 0,
};
