//! Emit a fixture's paired-core root module (paired.zig) from the
//! transpiled module's OWN export surface: the lockstep entry points
//! (`initialModel`/`update`/`commitModelRoot`, the subscriptions and
//! host-event channels the fixture actually exports, `rt`) bind the
//! PairedCore lanes, and every other public declaration — types, model
//! helpers, catalog constants, channel consts — re-exports from the
//! transpiled lane verbatim. Generated at build time (the
//! sidecar-extractor pattern), so the paired surface can never go stale
//! against the fixture: a fixture gaining or dropping a channel
//! regenerates the root, and the host adapter's export-presence
//! detection keeps seeing the fixture's true surface.

const std = @import("std");

/// The decls the paired implementation owns; everything else forwards
/// to the transpiled lane.
const lockstep_decls = [_][]const u8{
    "rt",
    "initialModel",
    "update",
    "commitModelRoot",
    "subscriptions",
    "frameMsg",
    "keyMsg",
    "pinchMsg",
    "commandMsg",
};

fn isLockstep(comptime name: []const u8) bool {
    for (lockstep_decls) |decl| {
        if (std.mem.eql(u8, decl, name)) return true;
    }
    return false;
}

pub fn pairedSource(comptime core: type) []const u8 {
    comptime {
        @setEvalBranchQuota(1_000_000);
        var out: []const u8 =
            \\//! Generated by the build (tests/compiled-core/gen_paired.zig):
            \\//! the fixture's paired-core root — lockstep entry points over
            \\//! both lanes, everything else re-exported from the transpiled
            \\//! module. Do not edit.
            \\const ts_lane = @import("ts_lane");
            \\const impl = @import("paired_core.zig").PairedCore(ts_lane, @import("shim_lane"));
            \\
            \\pub const rt = impl.rt;
            \\pub const paired_lanes = impl.paired_lanes;
            \\pub const initialModel = impl.initialModel;
            \\pub const update = impl.update;
            \\pub const commitModelRoot = impl.commitModelRoot;
            \\
        ;
        for ([_][]const u8{ "subscriptions", "frameMsg", "keyMsg", "pinchMsg", "commandMsg" }) |name| {
            if (@hasDecl(core, name)) {
                out = out ++ "pub const " ++ name ++ " = impl." ++ name ++ ";\n";
            }
        }
        for (@typeInfo(core).@"struct".decls) |decl| {
            if (isLockstep(decl.name)) continue;
            out = out ++ "pub const @\"" ++ decl.name ++ "\" = ts_lane.@\"" ++ decl.name ++ "\";\n";
        }
        return out;
    }
}

pub fn emitMain(comptime core: type, init: std.process.Init) !void {
    const source = comptime pairedSource(core);
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    if (args.len < 2) {
        var stderr_buffer: [256]u8 = undefined;
        var stderr_writer = std.Io.File.stderr().writerStreaming(init.io, &stderr_buffer);
        try stderr_writer.interface.print("usage: <gen-paired> <out path>\n", .{});
        try stderr_writer.interface.flush();
        std.process.exit(2);
    }
    if (std.fs.path.dirname(args[1])) |dir| {
        std.Io.Dir.cwd().createDirPath(init.io, dir) catch {};
    }
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = args[1], .data = source });
}

test "the paired root binds lockstep entries only for exported channels" {
    const FixtureModel = struct { n: i64 };
    const fixture = struct {
        pub const Model = FixtureModel;
        pub const Msg = union(enum) { ping, pong };
        pub fn initialModel() *const Model {
            unreachable;
        }
        pub fn update(model: *const Model, msg: Msg) *const Model {
            _ = msg;
            return model;
        }
        pub fn commitModelRoot(next: *const Model) *const Model {
            return next;
        }
        pub fn keyMsg(key: void) ?Msg {
            _ = key;
            return null;
        }
        pub const chromeMsg = "pong";
    };
    const source = comptime pairedSource(fixture);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const keyMsg = impl.keyMsg;") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "impl.frameMsg") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "impl.subscriptions") == null);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const @\"chromeMsg\" = ts_lane.@\"chromeMsg\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const @\"Model\" = ts_lane.@\"Model\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub const @\"Msg\" = ts_lane.@\"Msg\";") != null);
}
