//! soundboard model: the committed music catalog plus the playback,
//! search, navigation, and theming state the views bind to.
//!
//! The library is REAL data: `music_manifest.zon` (generated by
//! tools/prepare-example-music.sh and committed) is imported as a typed
//! value and flattened at comptime into the album/track tables below.
//! Albums carry a variable number of tracks, so each album records where
//! its run of tracks starts and how long it is — nothing here assumes a
//! fixed per-album stride.
//!
//! Playback is REAL audio through the runtime audio effect family:
//! pressing play issues `fx.playAudio` for the track's file and every
//! report — the load acknowledgment with the decoded duration, coarse
//! position ticks, the one completion at natural end, failures — arrives
//! as an `.audio_event` Msg through the ordinary update path. The audio
//! files themselves are gitignored (the prepare script downloads them);
//! a missing file surfaces as one `.failed` event and the model degrades
//! to an honest "assets not prepared" notice — browsing the catalog
//! never needs the mp3s.
//!
//! Everything the views show that is computable — filtered lists,
//! progress fractions, time labels — is derived per rebuild into the
//! build arena, never stored.
//!
//! Fixed capacities (loud by design, documented in the README):
//!   - the manifest's albums and tracks (comptime-flattened)
//!   - one registered cover image per album (of the runtime's 16 slots)
//!   - 16-entry play-next queue (a full queue drops the request, noted
//!     in `queue_dropped` so the UI could surface it)
//!   - 48-byte search buffer

const std = @import("std");
const native_sdk = @import("native_sdk");

const canvas = native_sdk.canvas;

pub const Effects = native_sdk.Effects(Msg);

// ------------------------------------------------------------------ library

/// The manifest's shape, typed so the zon import is checked field by
/// field at comptime — a drifted manifest is a compile error, not a
/// runtime surprise.
pub const ManifestTrack = struct { title: []const u8, file: []const u8, duration_ms: u32 };
pub const ManifestAlbum = struct { artist: []const u8, title: []const u8, year: u16, art: ?[]const u8, tracks: []const ManifestTrack };
pub const Catalog = struct { version: u32, albums: []const ManifestAlbum };

/// The committed catalog. Track `file` paths are relative to assets/;
/// album `art` paths are relative to src/ (the committed covers).
pub const catalog: Catalog = @import("music_manifest.zon");

pub const Album = struct {
    /// 1-based id; the registered cover `ImageId` matches it.
    id: u8,
    title: []const u8,
    artist: []const u8,
    year: u16,
    /// Cover fallback initials while the image is unregistered, derived
    /// from the album title at comptime.
    initials: []const u8,
    /// Committed cover path relative to src/, or null when the album
    /// shipped without art (initials stay, never a broken image).
    art: ?[]const u8,
    /// This album's run inside the flattened `tracks` table. Albums have
    /// VARIABLE track counts, so slicing is the only honest lookup — no
    /// fixed stride exists.
    track_start: u8,
    track_count: u8,
};

pub const Track = struct {
    /// 1-based id, unique across the library (also the audio effect key).
    id: u8,
    album: u8,
    /// 1-based position within the album.
    number: u8,
    title: []const u8,
    /// Playback path relative to the example root ("assets/" + the
    /// manifest's file), concatenated at comptime.
    path: []const u8,
    /// The manifest's duration — the display value until the platform's
    /// `.loaded` acknowledgment reports the decoded one.
    duration_ms: u32,
};

/// First letters of the title's first two words, uppercased — the cover
/// fallback the avatar shows while no image is registered.
fn initialsOf(comptime title: []const u8) []const u8 {
    comptime {
        var out: []const u8 = "";
        var word_start = true;
        for (title) |char| {
            if (char == ' ') {
                word_start = true;
                continue;
            }
            if (word_start and out.len < 2) out = out ++ &[_]u8{std.ascii.toUpper(char)};
            word_start = false;
        }
        return out;
    }
}

const total_tracks = blk: {
    var count: usize = 0;
    for (catalog.albums) |album| count += album.tracks.len;
    break :blk count;
};

/// The album table, flattened from the manifest at comptime with
/// sequential 1-based ids and each album's track run recorded.
pub const albums = blk: {
    var out: [catalog.albums.len]Album = undefined;
    var track_start: usize = 0;
    for (catalog.albums, 0..) |album, index| {
        out[index] = .{
            .id = index + 1,
            .title = album.title,
            .artist = album.artist,
            .year = album.year,
            .initials = initialsOf(album.title),
            .art = album.art,
            .track_start = track_start,
            .track_count = album.tracks.len,
        };
        track_start += album.tracks.len;
    }
    break :blk out;
};

/// The flattened track table: album order, sequential 1-based ids, and
/// each track's ready-to-play path baked at comptime.
pub const tracks = blk: {
    var out: [total_tracks]Track = undefined;
    var index: usize = 0;
    for (catalog.albums, 0..) |album, album_index| {
        for (album.tracks, 0..) |track, position| {
            out[index] = .{
                .id = index + 1,
                .album = album_index + 1,
                .number = position + 1,
                .title = track.title,
                .path = "assets/" ++ track.file,
                .duration_ms = track.duration_ms,
            };
            index += 1;
        }
    }
    break :blk out;
};

pub fn albumById(id: u8) *const Album {
    return &albums[id - 1];
}

pub fn trackById(id: u8) *const Track {
    return &tracks[id - 1];
}

pub fn albumTracks(album_id: u8) []const Track {
    const album = albumById(album_id);
    const start: usize = album.track_start;
    return tracks[start .. start + album.track_count];
}

// -------------------------------------------------------------- capacities

pub const max_queue = 16;
pub const max_search = 48;
/// The header bar's natural height, and the floor `header_height` falls
/// back to when no titlebar band overlays the content (fullscreen,
/// standard chrome, tests). Matches the tall hidden-inset band the
/// system reports through `on_chrome` — the band must not be taller
/// than the OS band, or the header's controls center below the traffic
/// lights the system centers within its own band.
pub const header_natural_height: f32 = 52;

/// Effect keys, model-owned identity (effect-key style). Audio playback
/// keys are the track ids themselves — one key namespace per channel.
pub const copy_key: u64 = 2;

/// The honest degraded state when a track's file cannot load (the audio
/// assets are gitignored; the prepare script downloads them). The
/// now-playing bar shows both lines so the user knows exactly what to
/// run — never a crash, never silence, and the catalog browses fine.
pub const assets_missing_title = "music assets not prepared";
pub const assets_missing_hint = "run tools/prepare-example-music.sh";

// ------------------------------------------------------------------- model

pub const Tab = enum { albums, songs };

pub const Msg = union(enum) {
    show_albums,
    show_songs,
    set_appearance: native_sdk.Appearance,
    /// Chrome overlay geometry (tall hidden-inset titlebar): the header
    /// pads its leading edge past the traffic lights and matches its
    /// height to the titlebar band. Delivered through `on_chrome`.
    chrome_changed: native_sdk.WindowChrome,
    search_edit: canvas.TextInputEvent,
    open_album: u8,
    close_album,
    play_album: u8,
    play_track: u8,
    toggle_play,
    next_track,
    prev_track,
    /// Seek slider changed; the reconciled value arrives through the
    /// `sync` hook (`seek_fraction`) before this message is applied.
    seeked,
    /// Every audio playback report: the load acknowledgment, position
    /// ticks, the one completion, and failures. Plain data — safe to
    /// read whole in update.
    audio_event: native_sdk.EffectAudio,
    /// Controlled scroll: each region's applied offset lands here and the
    /// view echoes it back, so a rebuild mid-gesture can never reset it.
    grid_scrolled: canvas.ScrollState,
    detail_scrolled: canvas.ScrollState,
    songs_scrolled: canvas.ScrollState,
    /// Context menu: queue a track to play after the current one.
    queue_track: u8,
    /// Context menu: copy the track title to the clipboard via `pbcopy`
    /// (the effects channel has no clipboard call today).
    copy_title: u8,
    copied: native_sdk.EffectExit,
};

pub const Model = struct {
    // Source-of-truth state only; everything else is derived per rebuild.
    tab: Tab = .albums,
    appearance: native_sdk.Appearance = .{},
    open_album: ?u8 = null,
    /// Controlled scroll offsets (album grid, album detail, all songs):
    /// the model observes the applied offset and echoes it back.
    grid_scroll: f32 = 0,
    detail_scroll: f32 = 0,
    /// Chrome overlay geometry from `on_chrome` (tall hidden-inset
    /// titlebar): the header leads with a spacer this wide so its
    /// controls clear the traffic lights, and matches its height to the
    /// titlebar band. Both fall back to the natural header when no band
    /// overlays the content (fullscreen, standard chrome, tests).
    chrome_leading: f32 = 0,
    header_height: f32 = header_natural_height,
    songs_scroll: f32 = 0,
    now: ?u8 = null, // playing track id
    playing: bool = false,
    elapsed_ms: u32 = 0,
    /// The loaded track's duration for display and seek math: the
    /// manifest value at start, replaced by the platform's decoded
    /// duration when the `.loaded` acknowledgment arrives (the platform
    /// is the authority once it has actually opened the file).
    now_duration_ms: u32 = 0,
    /// A track's file failed to load (the gitignored audio assets are
    /// not prepared, or the platform has no audio playback): playback is
    /// cleared and the now-playing bar shows the prepare hint instead.
    assets_missing: bool = false,
    queue: [max_queue]u8 = @splat(0),
    queue_len: usize = 0,
    queue_dropped: u32 = 0,
    search_buffer: canvas.TextBuffer(max_search) = .{},
    /// Seek slider value, mirrored from the runtime through `sync`.
    seek_fraction: f32 = 0,
    /// Registered cover ImageIds, index = album id - 1; 0 while the
    /// decode/registration has not succeeded (avatars fall back to
    /// initials, so a failed decode can never break the UI).
    covers: [albums.len]canvas.ImageId = @splat(0),
    /// Copy-to-clipboard bookkeeping: how many pbcopy spawns finished ok.
    copies_done: u32 = 0,
    copy_failed: bool = false,

    // ------------------------------------------------------------- queries

    pub fn search(model: *const Model) []const u8 {
        return model.search_buffer.text();
    }

    pub fn searching(model: *const Model) bool {
        return model.search().len > 0;
    }

    pub fn albumsShowing(model: *const Model) bool {
        return model.tab == .albums;
    }

    pub fn songsShowing(model: *const Model) bool {
        return model.tab == .songs;
    }

    pub fn colorScheme(model: *const Model) native_sdk.ColorScheme {
        return model.appearance.color_scheme;
    }

    pub fn coverFor(model: *const Model, album_id: u8) canvas.ImageId {
        return model.covers[album_id - 1];
    }

    pub fn nowTrack(model: *const Model) ?*const Track {
        const id = model.now orelse return null;
        return trackById(id);
    }

    /// The open album's title, for the detail page's markup heading
    /// (album_title.native binds it). Total over the model on purpose —
    /// markup bindings resolve on every rebuild — so it answers "" when
    /// no album is open (the grid page, where the fragment is not
    /// composed).
    pub fn openAlbumTitle(model: *const Model) []const u8 {
        const id = model.open_album orelse return "";
        return albumById(id).title;
    }

    pub fn hasNowPlaying(model: *const Model) bool {
        return model.now != null;
    }

    pub fn idle(model: *const Model) bool {
        return model.now == null;
    }

    /// Data-driven icon choice for the transport's primary button: the
    /// markup binds `icon="{playPauseIcon}"`, so ONE button swaps its
    /// glyph with playback state - no if/else arms, no shared key to
    /// keep its identity stable.
    pub fn playPauseIcon(model: *const Model) []const u8 {
        return if (model.playing) "pause" else "play";
    }

    pub fn nowPlayingCover(model: *const Model) canvas.ImageId {
        const track = model.nowTrack() orelse return 0;
        return model.coverFor(track.album);
    }

    pub fn nowPlayingInitials(model: *const Model) []const u8 {
        const track = model.nowTrack() orelse return "--";
        return albumById(track.album).initials;
    }

    /// The bar's first line doubles as the status line: the honest
    /// assets-not-prepared notice replaces the track title after a load
    /// failure, so the user is told what to run instead of hearing
    /// nothing.
    pub fn nowPlayingTitle(model: *const Model) []const u8 {
        if (model.assets_missing) return assets_missing_title;
        const track = model.nowTrack() orelse return "Nothing playing";
        return track.title;
    }

    pub fn nowPlayingArtist(model: *const Model) []const u8 {
        if (model.assets_missing) return assets_missing_hint;
        const track = model.nowTrack() orelse return "Pick an album or a song to start";
        return albumById(track.album).artist;
    }

    pub fn progressFraction(model: *const Model) f32 {
        if (model.now == null or model.now_duration_ms == 0) return 0;
        const fraction = @as(f32, @floatFromInt(model.elapsed_ms)) / @as(f32, @floatFromInt(model.now_duration_ms));
        return std.math.clamp(fraction, 0, 1);
    }

    pub fn elapsedLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "-:--";
        return formatMs(arena, model.elapsed_ms);
    }

    pub fn durationLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "-:--";
        return formatMs(arena, model.now_duration_ms);
    }

    /// Albums matching the search query, derived into the build arena.
    pub fn visibleAlbums(model: *const Model, arena: std.mem.Allocator) []const AlbumCell {
        const out = arena.alloc(AlbumCell, albums.len) catch return &.{};
        var count: usize = 0;
        for (&albums) |*album| {
            if (!model.albumMatches(album)) continue;
            out[count] = .{
                .id = album.id,
                .title = album.title,
                .artist = album.artist,
                .initials = album.initials,
                .cover = model.coverFor(album.id),
                .playing = model.playingAlbum() == album.id,
            };
            count += 1;
        }
        return out[0..count];
    }

    /// Library tracks matching the search query (title, artist, or album),
    /// derived into the build arena.
    pub fn visibleTracks(model: *const Model, arena: std.mem.Allocator) []const TrackRow {
        const out = arena.alloc(TrackRow, tracks.len) catch return &.{};
        var count: usize = 0;
        for (&tracks) |*track| {
            if (!model.trackMatches(track)) continue;
            out[count] = model.trackRow(arena, track, .with_album);
            count += 1;
        }
        return out[0..count];
    }

    /// One album's tracks for the detail view (never search-filtered: the
    /// detail page is the whole record).
    pub fn albumTrackRows(model: *const Model, arena: std.mem.Allocator, album_id: u8) []const TrackRow {
        const album_tracks = albumTracks(album_id);
        const out = arena.alloc(TrackRow, album_tracks.len) catch return &.{};
        for (album_tracks, 0..) |*track, index| {
            out[index] = model.trackRow(arena, track, .number_only);
        }
        return out;
    }

    pub fn playingAlbum(model: *const Model) u8 {
        const track = model.nowTrack() orelse return 0;
        return if (model.playing) track.album else 0;
    }

    fn albumMatches(model: *const Model, album: *const Album) bool {
        const query = model.search();
        if (query.len == 0) return true;
        return containsIgnoreCase(album.title, query) or containsIgnoreCase(album.artist, query);
    }

    fn trackMatches(model: *const Model, track: *const Track) bool {
        const query = model.search();
        if (query.len == 0) return true;
        const album = albumById(track.album);
        return containsIgnoreCase(track.title, query) or
            containsIgnoreCase(album.artist, query) or
            containsIgnoreCase(album.title, query);
    }

    const TrackRowStyle = enum { with_album, number_only };

    fn trackRow(model: *const Model, arena: std.mem.Allocator, track: *const Track, style: TrackRowStyle) TrackRow {
        const album = albumById(track.album);
        return .{
            .id = track.id,
            .number = std.fmt.allocPrint(arena, "{d}", .{track.number}) catch "",
            .title = track.title,
            .subtitle = switch (style) {
                .with_album => std.fmt.allocPrint(arena, "{s} — {s}", .{ album.artist, album.title }) catch "",
                .number_only => "",
            },
            .duration = formatMs(arena, track.duration_ms),
            .now = model.now == track.id,
            .playing = model.now == track.id and model.playing,
            .queued = model.isQueued(track.id),
        };
    }

    fn isQueued(model: *const Model, track_id: u8) bool {
        for (model.queue[0..model.queue_len]) |queued| {
            if (queued == track_id) return true;
        }
        return false;
    }

    // ------------------------------------------------------------ mutation

    fn pushQueue(model: *Model, track_id: u8) void {
        if (model.isQueued(track_id)) return;
        if (model.queue_len >= max_queue) {
            model.queue_dropped += 1;
            return;
        }
        model.queue[model.queue_len] = track_id;
        model.queue_len += 1;
    }

    fn popQueue(model: *Model) ?u8 {
        if (model.queue_len == 0) return null;
        const next = model.queue[0];
        for (model.queue[1..model.queue_len], 0..) |moved, slot| {
            model.queue[slot] = moved;
        }
        model.queue_len -= 1;
        return next;
    }
};

pub const AlbumCell = struct {
    id: u8,
    title: []const u8,
    artist: []const u8,
    initials: []const u8,
    cover: canvas.ImageId,
    playing: bool,
};

pub const TrackRow = struct {
    id: u8,
    number: []const u8,
    title: []const u8,
    subtitle: []const u8,
    duration: []const u8,
    /// This track is loaded in the now-playing bar (playing or paused).
    now: bool,
    playing: bool,
    queued: bool,
};

fn formatMs(arena: std.mem.Allocator, ms: u32) []const u8 {
    const total_seconds = ms / 1000;
    return std.fmt.allocPrint(arena, "{d}:{d:0>2}", .{ total_seconds / 60, total_seconds % 60 }) catch "";
}

fn containsIgnoreCase(haystack: []const u8, needle: []const u8) bool {
    if (needle.len == 0) return true;
    if (needle.len > haystack.len) return false;
    var index: usize = 0;
    while (index + needle.len <= haystack.len) : (index += 1) {
        if (std.ascii.eqlIgnoreCase(haystack[index .. index + needle.len], needle)) return true;
    }
    return false;
}

// ------------------------------------------------------------------ update

pub fn update(model: *Model, msg: Msg, fx: *Effects) void {
    switch (msg) {
        .show_albums => model.tab = .albums,
        .show_songs => model.tab = .songs,
        .set_appearance => |appearance| model.appearance = appearance,
        .chrome_changed => |chrome| {
            model.chrome_leading = chrome.insets.left;
            // Match the header to the titlebar band so its centered
            // controls share the traffic lights' centerline; the natural
            // height is the floor when no band overlays the content.
            model.header_height = @max(header_natural_height, chrome.insets.top);
        },
        .search_edit => |edit| model.search_buffer.apply(edit),
        .grid_scrolled => |state| model.grid_scroll = state.offset,
        .detail_scrolled => |state| model.detail_scroll = state.offset,
        .songs_scrolled => |state| model.songs_scroll = state.offset,
        .open_album => |id| {
            model.open_album = id;
            model.tab = .albums;
            // A fresh record opens at its top.
            model.detail_scroll = 0;
        },
        .close_album => model.open_album = null,
        .play_album => |id| startTrack(model, fx, albumTracks(id)[0].id),
        .play_track => |id| {
            if (model.now == id) {
                setPlaying(model, fx, !model.playing);
            } else {
                startTrack(model, fx, id);
            }
        },
        .toggle_play => {
            if (model.now == null) {
                startTrack(model, fx, tracks[0].id);
            } else {
                setPlaying(model, fx, !model.playing);
            }
        },
        .next_track => advance(model, fx),
        .prev_track => previous(model, fx),
        .seeked => {
            if (model.now != null) {
                const duration: f32 = @floatFromInt(model.now_duration_ms);
                const target: u32 = @intFromFloat(std.math.clamp(model.seek_fraction, 0, 1) * duration);
                // Optimistic mirror for the labels; the platform seek has
                // no echo — the next position tick reports from there.
                model.elapsed_ms = target;
                fx.seekAudio(target);
            }
        },
        .audio_event => |event| handleAudioEvent(model, fx, event),
        .queue_track => |id| model.pushQueue(id),
        .copy_title => |id| fx.spawn(.{
            .key = copy_key,
            .argv = &.{"/usr/bin/pbcopy"},
            .stdin = trackById(id).title,
            .on_exit = Effects.exitMsg(.copied),
        }),
        .copied => |exit| {
            if (exit.reason == .exited and exit.code == 0) {
                model.copies_done += 1;
                model.copy_failed = false;
            } else {
                model.copy_failed = true;
            }
        },
    }
}

/// Every playback report flows through here. The audio key is the track
/// id, so a straggler for a track the model no longer plays is dropped
/// by identity — never misattributed to the current one.
fn handleAudioEvent(model: *Model, fx: *Effects, event: native_sdk.EffectAudio) void {
    const now = model.now orelse return;
    if (event.key != now) return;
    switch (event.kind) {
        .loaded => {
            // The platform decoded the file: its duration is the
            // authority from here on (the manifest's estimate may differ
            // by a little).
            if (event.duration_ms > 0) model.now_duration_ms = @intCast(event.duration_ms);
            model.elapsed_ms = @intCast(event.position_ms);
            model.playing = event.playing;
        },
        .position => {
            model.elapsed_ms = @intCast(event.position_ms);
            if (event.duration_ms > 0) model.now_duration_ms = @intCast(event.duration_ms);
        },
        .completed => advance(model, fx),
        .failed, .rejected => {
            // The file could not load — the gitignored assets are not
            // prepared (or the host has no audio playback). Clear
            // playback and surface the prepare hint; the catalog keeps
            // browsing fine without any mp3s.
            model.assets_missing = true;
            model.now = null;
            model.playing = false;
            model.elapsed_ms = 0;
            model.now_duration_ms = 0;
        },
    }
}

fn startTrack(model: *Model, fx: *Effects, track_id: u8) void {
    const track = trackById(track_id);
    model.now = track_id;
    // `elapsed_ms` restarts here and advances with position events — it
    // is also the motion clock for the now-playing slide-in window, so
    // animation gating replays deterministically (no live clock read
    // anywhere).
    model.elapsed_ms = 0;
    model.now_duration_ms = track.duration_ms;
    // A fresh attempt clears the degraded notice; if the file is still
    // missing the `.failed` event raises it again.
    model.assets_missing = false;
    model.playing = true;
    // One player total: a new playAudio replaces whatever played before,
    // and the track id keys every event back to this playback.
    fx.playAudio(.{
        .key = track_id,
        .path = track.path,
        .on_event = Effects.audioMsg(.audio_event),
    });
}

/// Play/pause drive the platform player in place; the optimistic flag
/// keeps the transport responsive and the next audio event confirms it.
fn setPlaying(model: *Model, fx: *Effects, playing: bool) void {
    model.playing = playing;
    if (playing) {
        fx.resumeAudio();
    } else {
        fx.pauseAudio();
    }
}

/// The play-next queue wins; otherwise the next track in the same album,
/// wrapping at the end of the record.
fn advance(model: *Model, fx: *Effects) void {
    if (model.popQueue()) |queued| {
        startTrack(model, fx, queued);
        return;
    }
    const track = model.nowTrack() orelse return;
    const album_tracks = albumTracks(track.album);
    const next_index = @as(usize, track.number) % album_tracks.len;
    startTrack(model, fx, album_tracks[next_index].id);
}

/// Restart the current track when it is a few seconds in; otherwise the
/// previous track in the album, wrapping backwards.
fn previous(model: *Model, fx: *Effects) void {
    const track = model.nowTrack() orelse return;
    if (model.elapsed_ms > 3000) {
        model.elapsed_ms = 0;
        fx.seekAudio(0);
        return;
    }
    const album_tracks = albumTracks(track.album);
    const prev_index = (@as(usize, track.number) + album_tracks.len - 2) % album_tracks.len;
    startTrack(model, fx, album_tracks[prev_index].id);
}
