import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, writeFileSync } from "node:fs";
import { NativeApp, findWidget, type NativeSnapshot } from "@native-sdk/core/testing";

const backend = process.env.NATIVE_SDK_TEST_VIEW_BACKEND;
const button = (s: NativeSnapshot, name: string) => findWidget(s, { role: "button", name });
const compare = (snapshots: NativeSnapshot[]) => {
  const reference = process.env.NATIVE_SDK_TEST_VIEW_REFERENCE;
  if (!reference) return;
  const values = snapshots.map(({ viewBackend, ...s }) => s);
  if (backend === "zig") writeFileSync(`${reference}.navigation.json`, JSON.stringify(values));
  else assert.deepEqual(values, JSON.parse(readFileSync(`${reference}.navigation.json`, "utf8")));
};

test("toggle state, source reconciliation, focus, identities and replay match", async () => {
  const app = await NativeApp.start({ width: 900, height: 420 });
  try {
    let s = await app.snapshot();
    if (backend) assert.equal(s.viewBackend, backend);
    const snapshots = [s], view = button(s, "Light café").view;
    const lightId = button(s, "Light café").id, darkId = button(s, "Dark").id;
    const save = () => snapshots.push(s);
    const focused = (name: string) => { assert.equal(button(s, name).focused, true); save(); };
    const theme = (id: number, changes: number) => {
      assert.equal(s.model.theme, id); assert.equal(s.model.changes, changes);
      const names = ["System", "Light café", "Dark"];
      assert.equal(s.widgets.filter(w => names.includes(w.name) && w.selected).length, 1); save();
    };
    const format = (name: string, selected: boolean) => { assert.equal(button(s, name).selected, selected); save(); };
    theme(2, 0);
    s = await app.click(button(s, "Dark")); theme(4, 1);
    s = await app.key(view, "enter"); theme(4, 2);
    s = await app.key(view, "space"); theme(4, 3);
    s = await app.key(view, "arrowleft"); focused("Light café"); theme(4, 3);
    s = await app.key(view, "arrowleft"); focused("System");
    s = await app.key(view, "arrowleft"); focused("System");
    s = await app.key(view, "end"); focused("Dark");
    s = await app.key(view, "home"); focused("System");
    s = await app.key(view, "end"); focused("Dark");
    s = await app.key(view, "tab"); focused("Bold");
    s = await app.key(view, "space"); format("Bold", true); assert.equal(s.model.changes, 4);
    s = await app.key(view, "tab"); focused("Italic");
    s = await app.key(view, "enter"); format("Italic", true); format("Bold", true);
    s = await app.key(view, "arrowright"); focused("Underline");
    s = await app.key(view, "arrowright"); focused("Underline"); assert.equal(s.model.changes, 5);
    s = await app.key(view, "enter"); format("Underline", true);
    s = await app.key(view, "tab"); focused("Monospace");
    s = await app.key(view, "enter"); format("Monospace", true);
    s = await app.key(view, "arrowright"); focused("Strike");
    s = await app.key(view, "arrowright"); focused("Strike");
    s = await app.key(view, "home"); focused("Monospace");
    s = await app.key(view, "end"); focused("Strike");
    s = await app.key(view, "arrowleft"); focused("Monospace");
    s = await app.key(view, "space"); format("Monospace", false); assert.equal(s.model.changes, 8);
    s = await app.key(view, "shift+tab"); focused("Underline");
    s = await app.click(button(s, "Refresh")); assert.equal(s.model.refreshes, 1); save();
    for (const name of ["Bold", "Italic", "Underline"]) format(name, true);
    s = await app.click(button(s, "System")); theme(1, 9);
    s = await app.click(button(s, "Light café")); theme(2, 10);
    for (const name of ["Bold", "Italic", "Underline"]) format(name, true);
    const disabled = button(s, "Unavailable"), point = { x: disabled.bounds.x + 10, y: disabled.bounds.y + 10 };
    assert.equal(disabled.enabled, false);
    await app.pointer(disabled, "down", point);
    s = await app.pointer(disabled, "up", point); theme(2, 10);
    const system = button(s, "System"), start = { x: system.bounds.x + 10, y: system.bounds.y + 10 };
    await app.pointer(system, "down", start);
    s = await app.pointer(system, "cancel", start); theme(2, 10);
    s = await app.click(button(s, "Reverse")); save();
    assert.equal(button(s, "Light café").id, lightId); assert.equal(button(s, "Dark").id, darkId);
    s = await app.action(button(s, "Light café"), "focus"); save();
    s = await app.key(view, "arrowright"); focused("System");
    s = await app.key(view, "arrowright"); focused("System");
    s = await app.key(view, "arrowleft"); focused("Light café");
    s = await app.key(view, "arrowleft"); focused("Dark");
    s = await app.key(view, "end"); focused("System");
    s = await app.key(view, "home"); focused("Dark"); theme(2, 10);
    s = await app.click(button(s, "Hide light")); assert.equal(s.widgets.some(w => w.name === "Light café"), false); save();
    s = await app.click(button(s, "Refresh")); assert.equal(s.model.theme, 2); save();
    s = await app.click(button(s, "Hide light")); assert.equal(button(s, "Light café").id, lightId); theme(2, 10);
    s = await app.click(button(s, "Empty")); assert.equal(s.widgets.some(w => w.name === "System" || w.name === "Dark"), false); save();
    s = await app.click(button(s, "Refresh")); for (const name of ["Bold", "Italic", "Underline"]) format(name, true);
    s = await app.click(button(s, "Empty")); assert.equal(button(s, "Light café").id, lightId); theme(2, 10);
    s = await app.click(button(s, "Bold")); format("Bold", false); format("Italic", true); assert.equal(s.model.changes, 11);
    s = await app.action(button(s, "Italic"), "toggle"); format("Italic", false); format("Underline", true); assert.equal(s.model.changes, 12);
    s = await app.click(button(s, "Reset")); theme(2, 0); format("Underline", true);
    const replay = await app.verifyReplay();
    assert.deepEqual(replay.snapshot.model, s.model); assert.deepEqual(replay.snapshot.widgets, s.widgets);
    snapshots.push(replay.snapshot); compare(snapshots);
  } finally { await app.close(); }
});
