// Generated by tools/prepare-example-music.sh alongside music_manifest.zon.
// Album slices preserve manifest order; audio files are shared with Soundboard.
import { asciiBytes, utf8Bytes } from "@native-sdk/core";
export interface Album {
  readonly id: number; readonly artist: Uint8Array; readonly title: Uint8Array;
  readonly year: number; readonly art: Uint8Array | null;
  readonly track_start: number; readonly track_count: number;
}
export interface Track {
  readonly id: number; readonly album: number; readonly number: number;
  readonly title: Uint8Array; readonly file: Uint8Array; readonly path: Uint8Array;
  readonly duration_ms: number; readonly bytes: number;
}
export const url_base = asciiBytes("https://xksenynjs1imkkii.public.blob.vercel-storage.com");
export const albums: readonly Album[] = [
  { id: 1, artist: asciiBytes("Harbor Sleep"), title: asciiBytes("Exit Signs"), year: 2025, art: asciiBytes("art/exit-signs.jpg"), track_start: 0, track_count: 8 },
  { id: 2, artist: asciiBytes("Harbor Sleep"), title: asciiBytes("Blue Season"), year: 2025, art: asciiBytes("art/blue-season.jpg"), track_start: 8, track_count: 7 },
  { id: 3, artist: asciiBytes("Casino Hearts"), title: asciiBytes("Second Nature"), year: 2026, art: asciiBytes("art/second-nature.jpg"), track_start: 15, track_count: 9 },
  { id: 4, artist: asciiBytes("Worn Thin"), title: asciiBytes("No Good Way Out"), year: 2025, art: asciiBytes("art/no-good-way-out.jpg"), track_start: 24, track_count: 9 },
  { id: 5, artist: asciiBytes("Violet District"), title: asciiBytes("Glass Flowers"), year: 2025, art: asciiBytes("art/glass-flowers.jpg"), track_start: 33, track_count: 9 },
  { id: 6, artist: asciiBytes("Violet District"), title: asciiBytes("Night Bloom"), year: 2025, art: asciiBytes("art/night-bloom.jpg"), track_start: 42, track_count: 8 },
  { id: 7, artist: asciiBytes("St. Electric"), title: asciiBytes("Motion Picture"), year: 2025, art: asciiBytes("art/motion-picture.jpg"), track_start: 50, track_count: 9 },
  { id: 8, artist: asciiBytes("Color TV"), title: asciiBytes("Channel Surfing"), year: 2025, art: asciiBytes("art/channel-surfing.jpg"), track_start: 59, track_count: 9 },
];
export const tracks: readonly Track[] = [
  { id: 1, album: 1, number: 1, title: asciiBytes("Mile Marker West"), file: asciiBytes("music/exit-signs/mile-marker-west.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/mile-marker-west.mp3"), duration_ms: 164832, bytes: 3982923 },
  { id: 2, album: 1, number: 2, title: asciiBytes("Harvest Lot"), file: asciiBytes("music/exit-signs/harvest-lot.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/harvest-lot.mp3"), duration_ms: 46944, bytes: 1136278 },
  { id: 3, album: 1, number: 3, title: asciiBytes("Winter Birds"), file: asciiBytes("music/exit-signs/winter-birds.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/winter-birds.mp3"), duration_ms: 70824, bytes: 1661879 },
  { id: 4, album: 1, number: 4, title: asciiBytes("Tidepool Windows"), file: asciiBytes("music/exit-signs/tidepool-windows.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/tidepool-windows.mp3"), duration_ms: 86952, bytes: 1958331 },
  { id: 5, album: 1, number: 5, title: asciiBytes("Untitled"), file: asciiBytes("music/exit-signs/untitled.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/untitled.mp3"), duration_ms: 195000, bytes: 4382227 },
  { id: 6, album: 1, number: 6, title: asciiBytes("Cedar Ave"), file: asciiBytes("music/exit-signs/cedar-ave.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/cedar-ave.mp3"), duration_ms: 89160, bytes: 1911716 },
  { id: 7, album: 1, number: 7, title: asciiBytes("Sunday Call"), file: asciiBytes("music/exit-signs/sunday-call.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/sunday-call.mp3"), duration_ms: 131760, bytes: 2953006 },
  { id: 8, album: 1, number: 8, title: asciiBytes("Verse Starts Raw"), file: asciiBytes("music/exit-signs/verse-starts-raw.mp3"), path: asciiBytes("../soundboard/assets/music/exit-signs/verse-starts-raw.mp3"), duration_ms: 116712, bytes: 2556363 },
  { id: 9, album: 2, number: 1, title: asciiBytes("Summer Rental"), file: asciiBytes("music/blue-season/summer-rental.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/summer-rental.mp3"), duration_ms: 98544, bytes: 2174137 },
  { id: 10, album: 2, number: 2, title: asciiBytes("Cut The Harbor"), file: asciiBytes("music/blue-season/cut-the-harbor.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/cut-the-harbor.mp3"), duration_ms: 58992, bytes: 1362458 },
  { id: 11, album: 2, number: 3, title: asciiBytes("Greenhouse Hands"), file: asciiBytes("music/blue-season/greenhouse-hands.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/greenhouse-hands.mp3"), duration_ms: 103272, bytes: 2331628 },
  { id: 12, album: 2, number: 4, title: asciiBytes("Open Windows"), file: asciiBytes("music/blue-season/open-windows.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/open-windows.mp3"), duration_ms: 99432, bytes: 2340120 },
  { id: 13, album: 2, number: 5, title: asciiBytes("Morning Ferry"), file: asciiBytes("music/blue-season/morning-ferry.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/morning-ferry.mp3"), duration_ms: 75912, bytes: 1821721 },
  { id: 14, album: 2, number: 6, title: asciiBytes("Lucky Number"), file: asciiBytes("music/blue-season/lucky-number.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/lucky-number.mp3"), duration_ms: 79224, bytes: 1810104 },
  { id: 15, album: 2, number: 7, title: asciiBytes("Salt on the Dock"), file: asciiBytes("music/blue-season/salt-on-the-dock.mp3"), path: asciiBytes("../soundboard/assets/music/blue-season/salt-on-the-dock.mp3"), duration_ms: 83352, bytes: 1885660 },
  { id: 16, album: 3, number: 1, title: asciiBytes("Velvet Jackpot"), file: asciiBytes("music/second-nature/velvet-jackpot.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/velvet-jackpot.mp3"), duration_ms: 130872, bytes: 3112901 },
  { id: 17, album: 3, number: 2, title: asciiBytes("Second Nature"), file: asciiBytes("music/second-nature/second-nature.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/second-nature.mp3"), duration_ms: 79920, bytes: 1986436 },
  { id: 18, album: 3, number: 3, title: asciiBytes("Passenger Seat"), file: asciiBytes("music/second-nature/passenger-seat.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/passenger-seat.mp3"), duration_ms: 87840, bytes: 2084573 },
  { id: 19, album: 3, number: 4, title: asciiBytes("Casino Glow"), file: asciiBytes("music/second-nature/casino-glow.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/casino-glow.mp3"), duration_ms: 80040, bytes: 1941026 },
  { id: 20, album: 3, number: 5, title: asciiBytes("Better Luck"), file: asciiBytes("music/second-nature/better-luck.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/better-luck.mp3"), duration_ms: 66480, bytes: 1546394 },
  { id: 21, album: 3, number: 6, title: asciiBytes("Slow Motion"), file: asciiBytes("music/second-nature/slow-motion.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/slow-motion.mp3"), duration_ms: 63984, bytes: 1513418 },
  { id: 22, album: 3, number: 7, title: asciiBytes("Out of Reach"), file: asciiBytes("music/second-nature/out-of-reach.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/out-of-reach.mp3"), duration_ms: 67200, bytes: 1561803 },
  { id: 23, album: 3, number: 8, title: asciiBytes("New York 2AM"), file: asciiBytes("music/second-nature/new-york-2am.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/new-york-2am.mp3"), duration_ms: 104424, bytes: 2518971 },
  { id: 24, album: 3, number: 9, title: asciiBytes("Casino Hearts"), file: asciiBytes("music/second-nature/casino-hearts.mp3"), path: asciiBytes("../soundboard/assets/music/second-nature/casino-hearts.mp3"), duration_ms: 68640, bytes: 1618756 },
  { id: 25, album: 4, number: 1, title: asciiBytes("Nothing Left"), file: asciiBytes("music/no-good-way-out/nothing-left.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/nothing-left.mp3"), duration_ms: 68544, bytes: 1638313 },
  { id: 26, album: 4, number: 2, title: asciiBytes("Cheap Seats"), file: asciiBytes("music/no-good-way-out/cheap-seats.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/cheap-seats.mp3"), duration_ms: 94944, bytes: 2355960 },
  { id: 27, album: 4, number: 3, title: asciiBytes("No Good Way Out"), file: asciiBytes("music/no-good-way-out/no-good-way-out.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/no-good-way-out.mp3"), duration_ms: 23424, bytes: 540820 },
  { id: 28, album: 4, number: 4, title: asciiBytes("Worn Thin"), file: asciiBytes("music/no-good-way-out/worn-thin.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/worn-thin.mp3"), duration_ms: 57432, bytes: 1299862 },
  { id: 29, album: 4, number: 5, title: asciiBytes("White Flag Burn"), file: asciiBytes("music/no-good-way-out/white-flag-burn.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/white-flag-burn.mp3"), duration_ms: 432672, bytes: 10590412 },
  { id: 30, album: 4, number: 6, title: asciiBytes("Burn Slow"), file: asciiBytes("music/no-good-way-out/burn-slow.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/burn-slow.mp3"), duration_ms: 104952, bytes: 2405998 },
  { id: 31, album: 4, number: 7, title: asciiBytes("Back Again"), file: asciiBytes("music/no-good-way-out/back-again.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/back-again.mp3"), duration_ms: 51720, bytes: 1273271 },
  { id: 32, album: 4, number: 8, title: asciiBytes("Eastbound Cut"), file: asciiBytes("music/no-good-way-out/eastbound-cut.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/eastbound-cut.mp3"), duration_ms: 112152, bytes: 2685482 },
  { id: 33, album: 4, number: 9, title: asciiBytes("Glass in My Teeth"), file: asciiBytes("music/no-good-way-out/glass-in-my-teeth.mp3"), path: asciiBytes("../soundboard/assets/music/no-good-way-out/glass-in-my-teeth.mp3"), duration_ms: 42504, bytes: 1021086 },
  { id: 34, album: 5, number: 1, title: asciiBytes("Paper Satellite"), file: asciiBytes("music/glass-flowers/paper-satellite.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/paper-satellite.mp3"), duration_ms: 129792, bytes: 3101360 },
  { id: 35, album: 5, number: 2, title: asciiBytes("Mothbox Window"), file: asciiBytes("music/glass-flowers/mothbox-window.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/mothbox-window.mp3"), duration_ms: 163272, bytes: 3528103 },
  { id: 36, album: 5, number: 3, title: asciiBytes("Room 214"), file: asciiBytes("music/glass-flowers/room-214.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/room-214.mp3"), duration_ms: 143424, bytes: 3391513 },
  { id: 37, album: 5, number: 4, title: asciiBytes("Sleepwalking Violet"), file: asciiBytes("music/glass-flowers/sleepwalking-violet.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/sleepwalking-violet.mp3"), duration_ms: 204672, bytes: 4808268 },
  { id: 38, album: 5, number: 5, title: asciiBytes("Parallel Lines"), file: asciiBytes("music/glass-flowers/parallel-lines.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/parallel-lines.mp3"), duration_ms: 162024, bytes: 3795271 },
  { id: 39, album: 5, number: 6, title: asciiBytes("Pressed Petals"), file: asciiBytes("music/glass-flowers/pressed-petals.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/pressed-petals.mp3"), duration_ms: 145272, bytes: 3426559 },
  { id: 40, album: 5, number: 7, title: asciiBytes("Salt On Glass II"), file: asciiBytes("music/glass-flowers/salt-on-glass-ii.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/salt-on-glass-ii.mp3"), duration_ms: 152952, bytes: 3525465 },
  { id: 41, album: 5, number: 8, title: asciiBytes("Fade Away"), file: asciiBytes("music/glass-flowers/fade-away.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/fade-away.mp3"), duration_ms: 139392, bytes: 3178058 },
  { id: 42, album: 5, number: 9, title: asciiBytes("Summer Static"), file: asciiBytes("music/glass-flowers/summer-static.mp3"), path: asciiBytes("../soundboard/assets/music/glass-flowers/summer-static.mp3"), duration_ms: 63864, bytes: 1434174 },
  { id: 43, album: 6, number: 1, title: asciiBytes("Night Bloom"), file: asciiBytes("music/night-bloom/night-bloom.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/night-bloom.mp3"), duration_ms: 123264, bytes: 2863514 },
  { id: 44, album: 6, number: 2, title: asciiBytes("Japanese Maple"), file: asciiBytes("music/night-bloom/japanese-maple.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/japanese-maple.mp3"), duration_ms: 192264, bytes: 4319501 },
  { id: 45, album: 6, number: 3, title: asciiBytes("Last Light"), file: asciiBytes("music/night-bloom/last-light.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/last-light.mp3"), duration_ms: 142752, bytes: 3339817 },
  { id: 46, album: 6, number: 4, title: asciiBytes("Northbound Window"), file: asciiBytes("music/night-bloom/northbound-window.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/northbound-window.mp3"), duration_ms: 151800, bytes: 3472424 },
  { id: 47, album: 6, number: 5, title: asciiBytes("Glass Flowers"), file: asciiBytes("music/night-bloom/glass-flowers.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/glass-flowers.mp3"), duration_ms: 142560, bytes: 3116716 },
  { id: 48, album: 6, number: 6, title: asciiBytes("Salt On Glass"), file: asciiBytes("music/night-bloom/salt-on-glass.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/salt-on-glass.mp3"), duration_ms: 159792, bytes: 3645772 },
  { id: 49, album: 6, number: 7, title: asciiBytes("Palette Shift"), file: asciiBytes("music/night-bloom/palette-shift.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/palette-shift.mp3"), duration_ms: 154824, bytes: 3500500 },
  { id: 50, album: 6, number: 8, title: asciiBytes("White Noise"), file: asciiBytes("music/night-bloom/white-noise.mp3"), path: asciiBytes("../soundboard/assets/music/night-bloom/white-noise.mp3"), duration_ms: 139992, bytes: 3160898 },
  { id: 51, album: 7, number: 1, title: asciiBytes("Silver Frame"), file: asciiBytes("music/motion-picture/silver-frame.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/silver-frame.mp3"), duration_ms: 142344, bytes: 3240483 },
  { id: 52, album: 7, number: 2, title: asciiBytes("Running Lights"), file: asciiBytes("music/motion-picture/running-lights.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/running-lights.mp3"), duration_ms: 143784, bytes: 3264053 },
  { id: 53, album: 7, number: 3, title: asciiBytes("Slow Burn"), file: asciiBytes("music/motion-picture/slow-burn.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/slow-burn.mp3"), duration_ms: 40272, bytes: 960072 },
  { id: 54, album: 7, number: 4, title: asciiBytes("Open Road Sign"), file: asciiBytes("music/motion-picture/open-road-sign.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/open-road-sign.mp3"), duration_ms: 54792, bytes: 1265357 },
  { id: 55, album: 7, number: 5, title: asciiBytes("Fire Escape"), file: asciiBytes("music/motion-picture/fire-escape.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/fire-escape.mp3"), duration_ms: 154392, bytes: 3443978 },
  { id: 56, album: 7, number: 6, title: asciiBytes("Saint Electric"), file: asciiBytes("music/motion-picture/saint-electric.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/saint-electric.mp3"), duration_ms: 86424, bytes: 1917917 },
  { id: 57, album: 7, number: 7, title: asciiBytes("Reactive Hearts"), file: asciiBytes("music/motion-picture/reactive-hearts.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/reactive-hearts.mp3"), duration_ms: 77640, bytes: 1729998 },
  { id: 58, album: 7, number: 8, title: asciiBytes("Call It Love"), file: asciiBytes("music/motion-picture/call-it-love.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/call-it-love.mp3"), duration_ms: 122760, bytes: 2775291 },
  { id: 59, album: 7, number: 9, title: asciiBytes("Glassline Horizon"), file: asciiBytes("music/motion-picture/glassline-horizon.mp3"), path: asciiBytes("../soundboard/assets/music/motion-picture/glassline-horizon.mp3"), duration_ms: 118824, bytes: 2749472 },
  { id: 60, album: 8, number: 1, title: asciiBytes("Side B"), file: asciiBytes("music/channel-surfing/side-b.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/side-b.mp3"), duration_ms: 73992, bytes: 1548162 },
  { id: 61, album: 8, number: 2, title: asciiBytes("Last Broadcast"), file: asciiBytes("music/channel-surfing/last-broadcast.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/last-broadcast.mp3"), duration_ms: 71952, bytes: 1708346 },
  { id: 62, album: 8, number: 3, title: asciiBytes("VHS Summer"), file: asciiBytes("music/channel-surfing/vhs-summer.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/vhs-summer.mp3"), duration_ms: 130992, bytes: 3045958 },
  { id: 63, album: 8, number: 4, title: asciiBytes("Static in My Heart"), file: asciiBytes("music/channel-surfing/static-in-my-heart.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/static-in-my-heart.mp3"), duration_ms: 179904, bytes: 4172094 },
  { id: 64, album: 8, number: 5, title: asciiBytes("Late Checkout"), file: asciiBytes("music/channel-surfing/late-checkout.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/late-checkout.mp3"), duration_ms: 78000, bytes: 1889857 },
  { id: 65, album: 8, number: 6, title: asciiBytes("Apartment 4B"), file: asciiBytes("music/channel-surfing/apartment-4b.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/apartment-4b.mp3"), duration_ms: 111744, bytes: 2439480 },
  { id: 66, album: 8, number: 7, title: asciiBytes("Blue Screen"), file: asciiBytes("music/channel-surfing/blue-screen.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/blue-screen.mp3"), duration_ms: 80904, bytes: 1838327 },
  { id: 67, album: 8, number: 8, title: asciiBytes("Friday Lot Glow"), file: asciiBytes("music/channel-surfing/friday-lot-glow.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/friday-lot-glow.mp3"), duration_ms: 87384, bytes: 1870587 },
  { id: 68, album: 8, number: 9, title: asciiBytes("Static on Maple"), file: asciiBytes("music/channel-surfing/static-on-maple.mp3"), path: asciiBytes("../soundboard/assets/music/channel-surfing/static-on-maple.mp3"), duration_ms: 135672, bytes: 3265131 },
];
export function albumById(id: number): Album | undefined { return albums.find((album) => album.id === id); }
export function trackById(id: number): Track | undefined { return tracks.find((track) => track.id === id); }
