//! deck model: the same committed music catalog as `examples/soundboard`
//! (one manifest, two skins — the "same app, different identity" contrast
//! is the point) plus the playback, queue, search, and playlist-window
//! state the deck binds to.
//!
//! Playback is REAL: pressing play issues `fx.playAudio` against the
//! shared on-disk library and every report — the load acknowledgment
//! with the decoded duration, coarse position ticks while playing, the
//! one completion at natural end, failures — arrives as an
//! `.audio_event` Msg through the ordinary update path. The progress
//! clock (`elapsed_ms`) advances only on position events, so everything
//! derived from it (the marquee, the spectrum) freezes on pause because
//! the clock stops — the same deterministic contract the timer
//! simulation had, now fed by the platform player.
//!
//! A failed load (missing mp3s, a platform without audio) clears the
//! deck and lights the honest degraded state: the VFD marquee stamps
//! `NO MEDIA` and the channel line names the remedy
//! (`tools/prepare-example-music.sh`). Browsing, search, and queueing
//! never need the audio files — the catalog is committed.
//!
//! Everything the views show that is computable — the filtered ledger,
//! timecode labels, the 32-band spectrum — is derived per rebuild into
//! the build arena, never stored. The spectrum is a pure function of
//! (track id, elapsed ms): sum-of-sines shaped by a per-track seed and a
//! mid-weighted envelope; it visualizes the playback clock, not decoded
//! samples (an honest readout, not a fake FFT).
//!
//! Fixed capacities (loud by design, documented in the README):
//!   - the committed manifest's albums and tracks (comptime-derived
//!     tables; per-album track counts VARY, nothing assumes a stride)
//!   - 16-entry play-next queue (a full queue drops the request, counted
//!     in `queue_dropped`)
//!   - 48-byte search buffer
//!   - 32 spectrum bands

const std = @import("std");
const native_sdk = @import("native_sdk");

const canvas = native_sdk.canvas;

pub const Effects = native_sdk.Effects(Msg);

// ---------------------------------------------------------------- manifest

/// The manifest's own shapes, matching `music_manifest.zon` (generated by
/// `tools/prepare-example-music.sh`; the deck's copy is byte-identical to
/// the soundboard's). Track `file` paths are relative to the
/// SOUNDBOARD's assets directory — the mp3s live once on disk and both
/// examples play the same files.
pub const ManifestTrack = struct { title: []const u8, file: []const u8, duration_ms: u32 };
pub const ManifestAlbum = struct { artist: []const u8, title: []const u8, year: u16, art: ?[]const u8, tracks: []const ManifestTrack };
pub const Catalog = struct { version: u32, albums: []const ManifestAlbum };

/// The committed catalog: browsable without any gitignored audio on disk.
pub const catalog: Catalog = @import("music_manifest.zon");

/// Where the shared audio lives relative to the deck's working
/// directory: the soundboard's gitignored assets tree, prepared by
/// `tools/prepare-example-music.sh`.
pub const audio_root = "../soundboard/assets/";

pub const album_count = catalog.albums.len;
pub const track_count = blk: {
    var total: usize = 0;
    for (catalog.albums) |album| total += album.tracks.len;
    break :blk total;
};

// ------------------------------------------------------------------ library

pub const Album = struct {
    /// 1-based id; the registered cover image id derives from it
    /// (`main.coverImageId`).
    id: u8,
    title: []const u8,
    artist: []const u8,
    year: u16,
    /// Committed cover path relative to `src/` (null when the album's
    /// source art was absent at prepare time).
    art: ?[]const u8,
    /// This album's window into the flat `tracks` table. Counts VARY per
    /// album — never assume a stride.
    track_start: u16,
    track_count: u8,
};

pub const Track = struct {
    /// 1-based id, unique across the library.
    id: u8,
    album: u8,
    /// 1-based position within the album.
    number: u8,
    title: []const u8,
    /// Playable path (deck-relative into the soundboard's assets).
    path: []const u8,
    /// Manifest duration: the display default until the platform's
    /// `.loaded` acknowledgment reports the decoded duration.
    duration_ms: u32,
};

/// Flat album table derived from the manifest at comptime: ids are
/// 1-based positions, and each album records its slice of the flat
/// track table (variable counts, no stride arithmetic anywhere).
pub const albums: [album_count]Album = blk: {
    var out: [album_count]Album = undefined;
    var start: usize = 0;
    for (catalog.albums, 0..) |album, index| {
        out[index] = .{
            .id = index + 1,
            .title = album.title,
            .artist = album.artist,
            .year = album.year,
            .art = album.art,
            .track_start = start,
            .track_count = album.tracks.len,
        };
        start += album.tracks.len;
    }
    break :blk out;
};

/// Flat track table derived from the manifest at comptime, in album
/// order; the playable path is the comptime concat of the shared assets
/// root and the manifest's soundboard-relative file.
pub const tracks: [track_count]Track = blk: {
    var out: [track_count]Track = undefined;
    var index: usize = 0;
    for (catalog.albums, 0..) |album, album_index| {
        for (album.tracks, 0..) |track, track_index| {
            out[index] = .{
                .id = index + 1,
                .album = album_index + 1,
                .number = track_index + 1,
                .title = track.title,
                .path = audio_root ++ track.file,
                .duration_ms = track.duration_ms,
            };
            index += 1;
        }
    }
    break :blk out;
};

pub fn albumById(id: u8) *const Album {
    return &albums[id - 1];
}

pub fn trackById(id: u8) *const Track {
    return &tracks[id - 1];
}

pub fn albumTracks(album_id: u8) []const Track {
    const album = albumById(album_id);
    const start: usize = album.track_start;
    return tracks[start .. start + album.track_count];
}

// -------------------------------------------------------------- capacities

pub const max_queue = 16;
pub const max_search = 48;
pub const spectrum_bands = 32;
/// Marquee geometry: visible window in mono characters, and how much
/// playback time advances the scroll by one character. 22 characters of
/// bold mono at the view's pitch-snapped marquee scale (7 px pitch) fill
/// the VFD's text column with clear glass to spare on both sides (24 ran
/// flush against the right bevel).
pub const marquee_window = 22;
pub const marquee_step_ms: u32 = 500;

/// The honest degraded state the VFD wears after a failed load: the
/// marquee stamp, and the channel-line remedy naming the script that
/// prepares the shared gitignored audio.
pub const no_media_marquee = "NO MEDIA";
pub const no_media_remedy = "RUN TOOLS/PREPARE-EXAMPLE-MUSIC.SH";

/// Effect keys, model-owned identity (effect-key style). The audio
/// channel's key is the playing track's id — its own namespace, so it
/// never collides with the spawn key below.
pub const copy_key: u64 = 2;

// ------------------------------------------------------------------- model

pub const Msg = union(enum) {
    /// The PL key (and `primary+L`): the playlist window's open flag
    /// flips, and the windows_fn reconcile creates or closes the window.
    toggle_playlist,
    /// The USER closed the playlist window (titlebar close): the window
    /// is already gone as an optimistic echo; the model agrees here.
    playlist_closed,
    set_appearance: native_sdk.Appearance,
    /// Chrome overlay insets changed (hidden-inset titlebar): the cap
    /// band's leading pad follows the traffic lights.
    set_chrome_leading: f32,
    search_edit: canvas.TextInputEvent,
    clear_search,
    play_track: u8,
    toggle_play,
    next_track,
    prev_track,
    /// Seek slider changed; the reconciled value arrives through the
    /// `sync` hook (`seek_fraction`) before this message is applied.
    seeked,
    /// Output volume slider changed; same sync-hook contract
    /// (`volume_fraction`). Rides through to the platform player.
    volume_changed,
    /// Every playback report from the audio effect channel: loaded,
    /// position ticks, the one completion, failures.
    audio_event: native_sdk.EffectAudio,
    /// Context menu: queue a track to play after the current one.
    queue_track: u8,
    /// Context menu: copy the track title to the clipboard via `pbcopy`
    /// (soundboard's effect, unchanged: the effects channel has no
    /// clipboard call today).
    copy_title: u8,
    copied: native_sdk.EffectExit,
};

pub const Model = struct {
    // Source-of-truth state only; everything else is derived per rebuild.
    /// The playlist window's visibility channel: `windows_fn` declares
    /// the window exactly while this is set (presence IS visibility).
    playlist_open: bool = false,
    appearance: native_sdk.Appearance = .{},
    /// Chrome overlay insets (hidden-inset titlebar): the cap band pads
    /// its leading edge by this so the brand engraving clears the
    /// traffic lights. Delivered through `on_chrome` before first build.
    chrome_leading: f32 = 0,
    now: ?u8 = null, // loaded track id
    playing: bool = false,
    elapsed_ms: u32 = 0,
    /// The loaded track's duration as the deck knows it: the manifest
    /// value at load, replaced by the platform's decoded duration when
    /// the `.loaded` acknowledgment arrives.
    now_duration_ms: u32 = 0,
    /// A load failed (missing mp3s, a platform without audio): the VFD
    /// wears the NO MEDIA remedy until the next successful load attempt.
    media_failed: bool = false,
    queue: [max_queue]u8 = @splat(0),
    queue_len: usize = 0,
    queue_dropped: u32 = 0,
    search_buffer: canvas.TextBuffer(max_search) = .{},
    /// Seek slider value, mirrored from the runtime through `sync`.
    seek_fraction: f32 = 0,
    /// Output level, mirrored from the runtime through `sync` and
    /// applied to the platform player via `fx.setAudioVolume`.
    volume_fraction: f32 = 0.8,
    /// Copy-to-clipboard bookkeeping: how many pbcopy spawns finished ok.
    copies_done: u32 = 0,
    copy_failed: bool = false,
    /// Registered texture ImageIds (0 while unregistered): the brushed
    /// plate the main-window chrome lays under its machining and the
    /// carbon weave behind the playlist rack. Registered once in `boot`;
    /// a failed decode leaves the id 0 and the chrome stays pure vector —
    /// a bad asset can never break presentation.
    texture_plate: canvas.ImageId = 0,
    texture_weave: canvas.ImageId = 0,
    /// Registered album cover ImageIds, index = album id - 1; 0 while
    /// unregistered (the strict test decoder has no JPEG codec, so under
    /// the null platform every slot stays 0 and the sleeve pane degrades
    /// to its engraved plate — asserted in the suite).
    covers: [album_count]canvas.ImageId = @splat(0),

    // ------------------------------------------------------------- queries

    pub fn search(model: *const Model) []const u8 {
        return model.search_buffer.text();
    }

    pub fn searching(model: *const Model) bool {
        return model.search().len > 0;
    }

    pub fn playlistShowing(model: *const Model) bool {
        return model.playlist_open;
    }

    pub fn nowTrack(model: *const Model) ?*const Track {
        const id = model.now orelse return null;
        return trackById(id);
    }

    pub fn idle(model: *const Model) bool {
        return model.now == null;
    }

    pub fn mediaFailed(model: *const Model) bool {
        return model.media_failed;
    }

    pub fn coverFor(model: *const Model, album_id: u8) canvas.ImageId {
        return model.covers[album_id - 1];
    }

    /// The loaded track's registered cover, 0 when idle or unregistered
    /// (the sleeve pane degrades to its engraved plate).
    pub fn nowCover(model: *const Model) canvas.ImageId {
        const track = model.nowTrack() orelse return 0;
        return model.coverFor(track.album);
    }

    pub fn hasQueue(model: *const Model) bool {
        return model.queue_len > 0;
    }

    pub fn queueLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        return std.fmt.allocPrint(arena, "QUEUE {d}", .{model.queue_len}) catch "";
    }

    /// Status-strip counter: visible tracks over the library total.
    pub fn statusLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        return std.fmt.allocPrint(arena, "{d}/{d} TRK", .{ model.visibleTracks(arena).len, tracks.len }) catch "";
    }

    /// VFD channel readout: "TRK 07". Short by design — the album is
    /// already in the marquee, and the timecode rides the same line
    /// (round 1 caught the long form wrapping over the progress strip).
    pub fn channelLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        const track = model.nowTrack() orelse return "TRK --";
        return std.fmt.allocPrint(arena, "TRK {d:0>2}", .{track.id}) catch "";
    }

    /// The VFD marquee: title, artist, and album on one rotating line —
    /// the classic scroller, derived (never stored) as a pure function
    /// of the loaded track and the progress clock. The composed line
    /// rotates one step every `marquee_step_ms` of PLAYBACK time, so
    /// pause freezes it exactly like the spectrum (the position events
    /// stop, the clock stops) and the same model state always yields the
    /// same window of text. After a failed load the marquee stamps the
    /// NO MEDIA state instead.
    pub fn marqueeText(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.media_failed) return no_media_marquee;
        const track = model.nowTrack() orelse return "NO SIGNAL";
        const album = albumById(track.album);
        // ASCII-only composition: the rotation slices bytes, so a
        // multi-byte separator could split mid-codepoint at the seam.
        // 192 bytes cover the catalog's longest title/artist/album line.
        var compose_buffer: [192]u8 = undefined;
        var upper_buffer: [192]u8 = undefined;
        const line = std.fmt.bufPrint(&compose_buffer, "{s} /// {s} /// {s}  ", .{
            track.title, album.artist, album.title,
        }) catch return track.title;
        const full = upperTo(&upper_buffer, line);
        if (full.len <= marquee_window) return arena.dupe(u8, std.mem.trimEnd(u8, full, " /")) catch "";
        const offset = (model.elapsed_ms / marquee_step_ms) % full.len;
        const out = arena.alloc(u8, marquee_window) catch return "";
        for (out, 0..) |*byte, index| {
            byte.* = full[(offset + index) % full.len];
        }
        return out;
    }

    pub fn progressFraction(model: *const Model) f32 {
        if (model.now == null) return 0;
        if (model.now_duration_ms == 0) return 0;
        const fraction = @as(f32, @floatFromInt(model.elapsed_ms)) / @as(f32, @floatFromInt(model.now_duration_ms));
        return std.math.clamp(fraction, 0, 1);
    }

    pub fn elapsedLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "--:--";
        return formatMs(arena, model.elapsed_ms);
    }

    pub fn durationLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "--:--";
        return formatMs(arena, model.now_duration_ms);
    }

    /// The 32 spectrum band levels in [0, 1] — a pure function of the
    /// loaded track and the progress clock (see the module doc). Derived
    /// into the build arena per rebuild.
    pub fn spectrumLevels(model: *const Model, arena: std.mem.Allocator) []const f32 {
        const out = arena.alloc(f32, spectrum_bands) catch return &.{};
        const track = model.nowTrack() orelse {
            // Idle: the noise floor, a fixed comb so the display reads as
            // powered-on hardware rather than a dead widget.
            for (out, 0..) |*level, band| {
                level.* = if (band % 4 == 0) 0.05 else 0.02;
            }
            return out;
        };
        const seed: f32 = @floatFromInt(@as(u32, track.id) * 7 + 3);
        const phase = @as(f32, @floatFromInt(model.elapsed_ms)) / 1000.0;
        for (out, 0..) |*level, band| {
            const x: f32 = @floatFromInt(band);
            // Mid-weighted envelope: lows tall, highs rolled off.
            const envelope = 0.35 + 0.65 * @exp(-x * x / 420.0);
            const wave =
                0.6 * @abs(@sin(phase * (1.3 + seed * 0.01) + x * 0.55 + seed)) +
                0.4 * @abs(@sin(phase * 2.9 + x * 1.35 + seed * 0.5));
            level.* = std.math.clamp(0.06 + envelope * wave * 0.94, 0, 1);
        }
        return out;
    }

    /// The peak-hold trace the spectrum chart's line series binds: each
    /// band's cap, a hair above the bar. Derived from the bands, so it
    /// freezes with them when the progress clock stops.
    pub fn spectrumPeaks(model: *const Model, arena: std.mem.Allocator) []const f32 {
        const levels = model.spectrumLevels(arena);
        const out = arena.alloc(f32, levels.len) catch return levels;
        for (levels, out) |level, *peak| peak.* = @min(1, level + 0.04);
        return out;
    }

    /// Output meter level: the mean of the current spectrum, scaled by
    /// the volume fader — display state for the VU strip.
    pub fn outputLevel(model: *const Model, arena: std.mem.Allocator) f32 {
        const levels = model.spectrumLevels(arena);
        if (levels.len == 0) return 0;
        var sum: f32 = 0;
        for (levels) |level| sum += level;
        const mean = sum / @as(f32, @floatFromInt(levels.len));
        return std.math.clamp(mean * std.math.clamp(model.volume_fraction, 0, 1) * 1.6, 0, 1);
    }

    /// Ledger rows: the whole library as ONE flat list, narrowed by the
    /// search query, derived into the build arena.
    pub fn visibleTracks(model: *const Model, arena: std.mem.Allocator) []const TrackRow {
        const out = arena.alloc(TrackRow, tracks.len) catch return &.{};
        var count: usize = 0;
        for (&tracks) |*track| {
            if (!model.trackMatches(track)) continue;
            out[count] = model.trackRow(arena, track);
            count += 1;
        }
        return out[0..count];
    }

    /// Up-next rows for the playlist window's cue strip, in queue order.
    pub fn queueRows(model: *const Model, arena: std.mem.Allocator) []const TrackRow {
        const out = arena.alloc(TrackRow, model.queue_len) catch return &.{};
        for (model.queue[0..model.queue_len], 0..) |id, slot| {
            out[slot] = model.trackRow(arena, trackById(id));
        }
        return out;
    }

    fn trackMatches(model: *const Model, track: *const Track) bool {
        const query = model.search();
        if (query.len == 0) return true;
        const album = albumById(track.album);
        return containsIgnoreCase(track.title, query) or
            containsIgnoreCase(album.artist, query) or
            containsIgnoreCase(album.title, query);
    }

    fn trackRow(model: *const Model, arena: std.mem.Allocator, track: *const Track) TrackRow {
        const album = albumById(track.album);
        return .{
            .id = track.id,
            .number = std.fmt.allocPrint(arena, "{d:0>2}", .{track.id}) catch "",
            .title = track.title,
            .artist = album.artist,
            .duration = formatMs(arena, track.duration_ms),
            .now = model.now == track.id,
            .playing = model.now == track.id and model.playing,
            .queued = model.isQueued(track.id),
        };
    }

    fn isQueued(model: *const Model, track_id: u8) bool {
        for (model.queue[0..model.queue_len]) |queued| {
            if (queued == track_id) return true;
        }
        return false;
    }

    // ------------------------------------------------------------ mutation

    fn pushQueue(model: *Model, track_id: u8) void {
        if (model.isQueued(track_id)) return;
        if (model.queue_len >= max_queue) {
            model.queue_dropped += 1;
            return;
        }
        model.queue[model.queue_len] = track_id;
        model.queue_len += 1;
    }

    fn popQueue(model: *Model) ?u8 {
        if (model.queue_len == 0) return null;
        const next = model.queue[0];
        for (model.queue[1..model.queue_len], 0..) |moved, slot| {
            model.queue[slot] = moved;
        }
        model.queue_len -= 1;
        return next;
    }
};

pub const TrackRow = struct {
    id: u8,
    number: []const u8,
    title: []const u8,
    artist: []const u8,
    duration: []const u8,
    /// This track is loaded in the deck (playing or paused).
    now: bool,
    playing: bool,
    queued: bool,
};

fn formatMs(arena: std.mem.Allocator, ms: u32) []const u8 {
    const total_seconds = ms / 1000;
    return std.fmt.allocPrint(arena, "{d}:{d:0>2}", .{ total_seconds / 60, total_seconds % 60 }) catch "";
}

fn containsIgnoreCase(haystack: []const u8, needle: []const u8) bool {
    if (needle.len == 0) return true;
    if (needle.len > haystack.len) return false;
    var index: usize = 0;
    while (index + needle.len <= haystack.len) : (index += 1) {
        if (std.ascii.eqlIgnoreCase(haystack[index .. index + needle.len], needle)) return true;
    }
    return false;
}

/// ASCII-uppercase into a fixed buffer (library titles are ASCII); the
/// caller's arena copy happens in the formatting call.
fn upperTo(buffer: []u8, source: []const u8) []const u8 {
    const len = @min(buffer.len, source.len);
    for (source[0..len], 0..) |byte, index| {
        buffer[index] = std.ascii.toUpper(byte);
    }
    return buffer[0..len];
}

// ------------------------------------------------------------------ update

pub fn update(model: *Model, msg: Msg, fx: *Effects) void {
    switch (msg) {
        .toggle_playlist => model.playlist_open = !model.playlist_open,
        .playlist_closed => model.playlist_open = false,
        .set_appearance => |appearance| model.appearance = appearance,
        .set_chrome_leading => |leading| model.chrome_leading = leading,
        .search_edit => |edit| model.search_buffer.apply(edit),
        .clear_search => model.search_buffer.apply(.clear),
        .play_track => |id| {
            if (model.now == id) {
                setPlaying(model, fx, !model.playing);
            } else {
                startTrack(model, fx, id);
            }
        },
        .toggle_play => {
            if (model.now == null) {
                startTrack(model, fx, tracks[0].id);
            } else {
                setPlaying(model, fx, !model.playing);
            }
        },
        .next_track => advance(model, fx),
        .prev_track => previous(model, fx),
        .seeked => {
            if (model.now != null) {
                const duration: f32 = @floatFromInt(model.now_duration_ms);
                const target: u32 = @intFromFloat(std.math.clamp(model.seek_fraction, 0, 1) * duration);
                // Optimistic clock move; the platform's next position
                // tick reports from the sought point and re-confirms it.
                model.elapsed_ms = target;
                fx.seekAudio(target);
            }
        },
        .volume_changed => {
            model.volume_fraction = std.math.clamp(model.volume_fraction, 0, 1);
            fx.setAudioVolume(model.volume_fraction);
        },
        .audio_event => |event| handleAudio(model, fx, event),
        .queue_track => |id| model.pushQueue(id),
        .copy_title => |id| fx.spawn(.{
            .key = copy_key,
            .argv = &.{"/usr/bin/pbcopy"},
            .stdin = trackById(id).title,
            .on_exit = Effects.exitMsg(.copied),
        }),
        .copied => |exit| {
            if (exit.reason == .exited and exit.code == 0) {
                model.copies_done += 1;
                model.copy_failed = false;
            } else {
                model.copy_failed = true;
            }
        },
    }
}

/// One playback report from the audio channel. Events carry the key the
/// channel resolved them against; a straggler for a replaced track (the
/// deck already started something else) is dropped rather than applied
/// to the wrong record.
fn handleAudio(model: *Model, fx: *Effects, event: native_sdk.EffectAudio) void {
    const id = model.now orelse return;
    if (event.key != @as(u64, id)) return;
    switch (event.kind) {
        .loaded => {
            // The platform's decoded duration replaces the manifest's
            // display default.
            model.now_duration_ms = clampMs(event.duration_ms);
        },
        .position => {
            // The progress clock: everything derived from playback time
            // (marquee, spectrum, timecode) advances here and ONLY here,
            // so pause freezes it all deterministically.
            model.elapsed_ms = clampMs(event.position_ms);
        },
        // Natural end: the play-next queue wins, else album order.
        .completed => advance(model, fx),
        // Missing/unreadable file or a platform without audio playback
        // (`failed`), or a path the effects layer refused (`rejected` —
        // impossible for these comptime paths, honest anyway): clear the
        // deck and light the NO MEDIA remedy. Never a crash, never
        // silence.
        .failed, .rejected => {
            model.now = null;
            model.playing = false;
            model.elapsed_ms = 0;
            model.now_duration_ms = 0;
            model.media_failed = true;
        },
    }
}

fn clampMs(ms: u64) u32 {
    return @intCast(@min(ms, std.math.maxInt(u32)));
}

fn startTrack(model: *Model, fx: *Effects, track_id: u8) void {
    const track = trackById(track_id);
    model.now = track_id;
    model.elapsed_ms = 0;
    // Display default until `.loaded` reports the decoded duration.
    model.now_duration_ms = track.duration_ms;
    // A fresh load attempt is the retry path out of the NO MEDIA state.
    model.media_failed = false;
    model.playing = true;
    // One player is the whole surface: a new playAudio replaces whatever
    // played before, and the track id is the channel key echoed in every
    // event for this playback.
    fx.playAudio(.{
        .key = track_id,
        .path = track.path,
        .on_event = Effects.audioMsg(.audio_event),
    });
    // Keep the platform player honest with the VOL fader from the very
    // first load (the channel default is full volume).
    fx.setAudioVolume(std.math.clamp(model.volume_fraction, 0, 1));
}

/// Play/pause ride the audio channel's transport: pause holds the
/// player in place (position events stop, so the clock and everything
/// derived from it freeze), resume continues from the same point.
fn setPlaying(model: *Model, fx: *Effects, playing: bool) void {
    model.playing = playing;
    if (playing) {
        fx.resumeAudio();
    } else {
        fx.pauseAudio();
    }
}

/// The play-next queue wins; otherwise the next track in the same album,
/// wrapping at the end of the record. Per-album lengths vary, so the
/// wrap arithmetic runs on the album's own slice.
fn advance(model: *Model, fx: *Effects) void {
    if (model.popQueue()) |queued| {
        startTrack(model, fx, queued);
        return;
    }
    const track = model.nowTrack() orelse return;
    const album_tracks = albumTracks(track.album);
    const next_index = @as(usize, track.number) % album_tracks.len;
    startTrack(model, fx, album_tracks[next_index].id);
}

/// Restart the current track when it is a few seconds in; otherwise the
/// previous track in the album, wrapping backwards.
fn previous(model: *Model, fx: *Effects) void {
    const track = model.nowTrack() orelse return;
    if (model.elapsed_ms > 3000) {
        model.elapsed_ms = 0;
        fx.seekAudio(0);
        return;
    }
    const album_tracks = albumTracks(track.album);
    const prev_index = (@as(usize, track.number) + album_tracks.len - 2) % album_tracks.len;
    startTrack(model, fx, album_tracks[prev_index].id);
}
