export const PAGE_TITLES: Record<string, string> = {
  "": "Build Native Apps\nwith Zig, Web, and OS Surfaces",
  "quick-start": "Quick Start",
  "app-model": "App Model",
  frontend: "Frontend Projects",
  "native-surfaces": "Native Surfaces",
  windows: "Windows",
  webviews: "Multiple WebViews",
  "keyboard-shortcuts": "Keyboard Shortcuts",
  commands: "Commands",
  bridge: "Bridge",
  "bridge/builtin-commands": "Builtin Commands",
  dialogs: "Dialogs",
  menus: "Menus",
  "native-controls": "Native Controls",
  "built-in-components": "Built-in Components",
  capabilities: "Capabilities",
  "platform-support": "Platform Support",
  tray: "System Tray",
  security: "Security",
  cli: "CLI Reference",
  "cli/dev": "Dev Server",
  packaging: "Packaging",
  "packaging/signing": "Code Signing",
  updates: "Updates",
  "app-zon": "app.zon Reference",
  debugging: "Debugging",
  "debugging/doctor": "zero-native doctor",
  automation: "Automation",
  testing: "Testing",
  "testing/ci": "Testing in CI",
  extensions: "Extensions",
  embed: "Embedded App",
  "web-engines": "Web Engines",
  packages: "Package Distribution",
};

export function getPageTitle(slug: string): string | null {
  return slug in PAGE_TITLES ? PAGE_TITLES[slug]! : null;
}
